conversation_script_1 = [
    {"sender": "A", "message": "Thứ khỏe rồi đi thôi.", "response": "B", "reply": "được bro, chỗ nào vip vậy?"},
    {"sender": "B", "message": "Đi cả ngày ko update anh em ơi.", "response": "A", "reply": "tải app về chưa? liên kết acc trên web chưa?"},
    {"sender": "A", "message": "Rồi ad, hôm qua đi thì đc hôm nay ko thấy update.", "response": "B", "reply": "vào web liên kết lại phát nữa. trên andiroi update chậm lắm."},
    {"sender": "B", "message": "chứ iphone cái 1 à.", "response": "A", "reply": "sida quá."},
    {"sender": "A", "message": "đc rồi.", "response": "B", "reply": "thank ad."},
    {"sender": "B", "message": "xếp hạng mấy vậy?", "response": "A", "reply": "500 rồi, xong 17 game, đang join 25 game."},
    {"sender": "A", "message": "nốt đi.", "response": "B", "reply": "15 nhiệm vụ đa dạng dễ dàng hoàn thành cho trader mới."},
    {"sender": "B", "message": "nhanh tay tham gia, phần thưởng giá trị cho người đầu tiên!", "response": "A", "reply": "cũng định làm mà SH250i k có bằng đi."},
    {"sender": "A", "message": "Base. Clank coin. Vào xổ số x5 ae ơi.", "response": "B", "reply": "kiếm lambo thôi thầy!"},
    {"sender": "B", "message": "Vậy mình người dùng cũ. Chim cút khỏi okx à?", "response": "A", "reply": "xem lambo chia nát."},
    {"sender": "A", "message": "E xin link vô mua a ơi.", "response": "B", "reply": "Nhanh ko dowtrend."},
    {"sender": "B", "message": "Sol bay ác thế mà bags k nổ đi còn chờ đợi gì nữa nhở.", "response": "A", "reply": "Sâu giá này thì mua về lm gì nhỉ."},
    {"sender": "A", "message": "Xổ số ae, min x2.", "response": "B", "reply": "ern lv35 max đk 13k. Thế mua sâu 15k vêd lm mẹ gì nhỉ."},
    {"sender": "B", "message": "Dc hoàn thêm 0.007 sui.", "response": "A", "reply": "x4 LOL!"},
    {"sender": "A", "message": "Bú ác.", "response": "B", "reply": "bào kiểu này rồi ko ai chơi lại khóc."},
    {"sender": "A", "message": "Mua sâu cúng hay làm gì má?", "response": "B", "reply": "Clm đen rồi ngày đầu chạy lại đau mắt cá chân."},
    {"sender": "B", "message": "Thôi toang 6 ngày còn lại r.", "response": "A", "reply": "Sao cno nhận đc."},
    {"sender": "A", "message": "Mà mình ko nhận đc nhỉ.", "response": "B", "reply": "bro join đc game này k."},
    {"sender": "B", "message": "Ko join đc nên mới hỏi.", "response": "A", "reply": "Dễ gì mà lên đ thế."},
    {"sender": "A", "message": "Lên vững chứ ko phải giật.", "response": "B", "reply": "nhanh hay chậm gì cũng chắc hết."},
    {"sender": "B", "message": "Công nhận.", "response": "A", "reply": "anh em mua stake di ido."},
    {"sender": "A", "message": "Sắp bay tới nơi.", "response": "B", "reply": "Giờ stake là đẹp."},
    {"sender": "B", "message": "come and arrest me.", "response": "A", "reply": "clm."},
    {"sender": "A", "message": "lắm ng tây vậy.", "response": "B", "reply": "Để xem."},
    {"sender": "B", "message": "Ese làm gì tiếp theo.", "response": "A", "reply": "Dạo này nhiều sự kiện quá."},
    {"sender": "A", "message": "Đúng r.", "response": "B", "reply": "Càng ngày càng có niềm tin."},
    {"sender": "B", "message": "Lại càng có động lực.", "response": "A", "reply": "Để chờ thêm."},
    {"sender": "A", "message": "Chứ gì nữa.", "response": "B", "reply": "chăm vay."},
    {"sender": "B", "message": "Đù.", "response": "A", "reply": "Éo ai được quà rồi."},
    {"sender": "A", "message": "Ese sắp list thêm CEX tier 1.", "response": "B", "reply": "Chuẩn bị bung lụa tiếp nhoá."},
    {"sender": "B", "message": "Oh.", "response": "A", "reply": "Tier 1 chắc binance."},
    {"sender": "A", "message": "gn.", "response": "B", "reply": "gud moning."},
    {"sender": "B", "message": "trường chào tân tráy quá.", "response": "A", "reply": "xem voi."},
    {"sender": "A", "message": "có ai the.", "response": "B", "reply": "Bigdaddy Emily sir."},
    {"sender": "B", "message": "Lê Bảo Minh Nhật.", "response": "A", "reply": "lineup chính thức là v."},
    {"sender": "A", "message": "này là ai.", "response": "B", "reply": "len tít tót sir."},
    {"sender": "B", "message": "chac ko hot.", "response": "A", "reply": "line up chính thức là v mà hqua lòi đâu ra Nam Per, Hoàng Cửu Bảo với Hoàng Tử Ếch."},
    {"sender": "A", "message": "thich ne.", "response": "B", "reply": "ổn hơn roi do."},
    {"sender": "B", "message": "cháy nhất Bắc Từ Liêm.", "response": "A", "reply": "có hát ko thầy."},
    {"sender": "A", "message": "có sir.", "response": "B", "reply": "Có ny ko?"},
    {"sender": "B", "message": "soon sir.", "response": "A", "reply": "Bú ko."},
    {"sender": "A", "message": "Chart đẹp vl.", "response": "B", "reply": "trend depin."},
    {"sender": "B", "message": "cho tele còn 10k.", "response": "A", "reply": "mua 1 lố rồi quay lại trend tele cũng được."},
    {"sender": "A", "message": "lạc quan quá síp.", "response": "B", "reply": "buy Op hold được rồi đó."},
    {"sender": "B", "message": "tầm này lạc quanlaf phải buy Pi Lét Quốc mà hold chứ.", "response": "A", "reply": "Hmmm."},
    {"sender": "A", "message": "pi víp quá e k đào.", "response": "B", "reply": "đào mtz thui."},
    {"sender": "B", "message": "ếch nhiêu tền là đủ dùng các síp nhỉ.", "response": "A", "reply": "399đ."},
    {"sender": "A", "message": "vkl.", "response": "B", "reply": "hèn gì síp bị elon khoá."},
    {"sender": "B", "message": "Hmmmm 399.", "response": "A", "reply": "Nó thả 7day die."},
    {"sender": "A", "message": "em mua từ 10k đến 20k có fl 20.", "response": "B", "reply": "chứ loại 5k e k dám."},
    {"sender": "B", "message": "a buy lúc 1.55 rồi.", "response": "A", "reply": "Á đù síp."},
    {"sender": "A", "message": "Trốn vk online.", "response": "B", "reply": "Ng có tiền gì cũng buy."},
    {"sender": "B", "message": "bth giờ này a vẫn onl mà.", "response": "A", "reply": "On claim mtz ?"},
    {"sender": "A", "message": "cái nào khó hỏi e.", "response": "B", "reply": "em gửi cái này."},
    {"sender": "B", "message": "khó.", "response": "A", "reply": "lên mmo mua."},
    {"sender": "A", "message": "nó mở mấy bữa n lại khóa cay vc.", "response": "B", "reply": "nhiêu cái nữa."},
    {"sender": "B", "message": "thiếu ý tưởng quá.", "response": "A", "reply": "1000 cái."},
    {"sender": "A", "message": "hmmm, k làm gì sao cứ khoá nhỉ.", "response": "B", "reply": "có dùng ip gì k síp."},
    {"sender": "B", "message": "Có lúc làm web 1 ip.", "response": "A", "reply": "Trên đt 1 ip khác."},
    {"sender": "A", "message": "Đậu.", "response": "B", "reply": "Vậy bth mà."},
    {"sender": "B", "message": "Thiếu 30 cái nữa hả.", "response": "A", "reply": "Sếp làm bn em lấy hết."},
    {"sender": "A", "message": "Xong gửi e ví.", "response": "B", "reply": "Mà nghỉ đi."},
    {"sender": "B", "message": "1,2 hôm có ý tưởng rồi bắt đầu.", "response": "A", "reply": "Editor."},
    {"sender": "A", "message": "Hhhh ko.", "response": "B", "reply": "Ý tưởng nhanh nhất lag đi copy rồi sửa."},
    {"sender": "B", "message": "Hiện tại chưa cần gấp.", "response": "A", "reply": "Để em sài hết đã."},
    {"sender": "A", "message": "Ủa cái plena kia.", "response": "B", "reply": "Nhiều mạng qua làm cái nào được."},
    {"sender": "B", "message": "Cái nào gas rẻ thì làm síp.", "response": "A", "reply": "Matic l2..."},
    {"sender": "A", "message": "Cứ cái nào là exp là múc hết hả.", "response": "B", "reply": "Né bnb avax ra."},
    {"sender": "B", "message": "Gas hơi cao.", "response": "A", "reply": "Oki."},
    {"sender": "A", "message": "Xong làm zealy.", "response": "B", "reply": "Mà zealy đang đua top với em dó."},
    {"sender": "B", "message": "Quần què toàn lagm x sợ vãi.", "response": "A", "reply": "Em làm tuốt."},
    {"sender": "A", "message": "1 lên voi 2 xuống x.", "response": "B", "reply": "Hhhh."},
    {"sender": "B", "message": "Làm bot tele plena. Có nhiệm vụ mint nft 1$.", "response": "A", "reply": "Cân nhădc."},
    {"sender": "A", "message": "Mạng gì ó.", "response": "B", "reply": "Quên r síp join tele nó hiện."},
    {"sender": "B", "message": "Oki.", "response": "A", "reply": "Hình như matic."},
    {"sender": "A", "message": "Rút tiền từ ví plena rút bằng $.", "response": "B", "reply": "Nên làm 1 ví chill."},
    {"sender": "B", "message": "Lagm chip hả tưởng vắt kiệt sức hhhh.", "response": "A", "reply": "1 acc chill síp."},
    {"sender": "A", "message": "Em 3x.", "response": "B", "reply": "Nó toag."},
    {"sender": "B", "message": "Làm tay 30acc.", "response": "A", "reply": "Hết nửa ngày à."},
    {"sender": "A", "message": "Trước khi làm thuyền trưởng.", "response": "B", "reply": "Thì con tàu chỉ mình tui."},
    {"sender": "B", "message": "Biến kẻ thù thành bạn. Là cách làm của mafia.", "response": "A", "reply": "ntn dc thì a đi xem tụi nó làm cái nào dễ."},
    {"sender": "A", "message": "a lấy về a sửa cho.", "response": "B", "reply": "được síp cho cái logo hình tròn, thêm tí chữ là oke."},
    {"sender": "B", "message": "khi nào a rảnh ý, em cần sll lớn mà a nên chỉnh bằng power point.", "response": "A", "reply": "hình này ok nè a."},
    {"sender": "A", "message": "biết chỉnh lại ó.", "response": "B", "reply": "A đi trông con đã."},
    {"sender": "B", "message": "okay síp.", "response": "A", "reply": "có gì rảnh giúp em nha."},
    {"sender": "A", "message": "Xíu gửi zô đâu z.", "response": "B", "reply": "nhờ 2 síp vô chơi 1 ván game cho nó tính ref với."},
    {"sender": "B", "message": "Hâhha.", "response": "A", "reply": "Ib box e."},
    {"sender": "A", "message": "Để e.", "response": "B", "reply": "Tag 2 síp đó."},
    {"sender": "B", "message": "cái này sao rồi síp.", "response": "A", "reply": "Nó cứ bị treo ấy a ạ."},
    {"sender": "A", "message": "tháng 12 TGE thì phải.", "response": "B", "reply": "lúc a bảo đó."},
    {"sender": "B", "message": "có chơi mà chơi nó toàn bị vầy.", "response": "A", "reply": "éo làm đc gì ko bị lose."},
    {"sender": "A", "message": "cay vcl.", "response": "B", "reply": "1000 cái nha."},
    {"sender": "B", "message": "Ước mơ của tôi.", "response": "A", "reply": "1 chos bằng 1 pen house."},
    {"sender": "A", "message": "này là hết nước đi mà.", "response": "B", "reply": "đủ rồi, thanks 2 ní."},
    {"sender": "B", "message": "Thánh ộp pô.", "response": "A", "reply": "Rank gì rồi síp."},
    {"sender": "A", "message": "Có tiền cứ đưa vợ hoặc nuôi vk tk khác nha các síp.", "response": "B", "reply": "Master."},
    {"sender": "B", "message": "Đừng đưa cho kol.", "response": "A", "reply": "yup."},
    {"sender": "A", "message": "xong đi ngủ.", "response": "B", "reply": "Đi guốc trong bụng."},
    {"sender": "B", "message": "thôi xong rồi.", "response": "A", "reply": "ngủ thâu, bibi."},
    {"sender": "A", "message": "e có bú ko.", "response": "B", "reply": "Làm cho e 100 con meme với síp."},
    {"sender": "B", "message": "Em trả lương.", "response": "A", "reply": "Bú gì sir."},
    {"sender": "A", "message": "tháng sau.", "response": "B", "reply": "K them."},
    {"sender": "B", "message": "Bú ngày 8$ ngon r a.", "response": "A", "reply": "Kkk."},
    {"sender": "A", "message": "uk.", "response": "B", "reply": "Rules khó k chơi."},
    {"sender": "B", "message": "khó thiệt.", "response": "A", "reply": "a up dàn ref lên để farm nên chơi luôn."},
    {"sender": "A", "message": "mà nghe khó.", "response": "B", "reply": "a mới 3$."},
    {"sender": "B", "message": "9 acc mà 3$.", "response": "A", "reply": "Vay vợ."},
    {"sender": "A", "message": "5tr úp hết đi a.", "response": "B", "reply": "Vay NH 500 tr."},
    {"sender": "B", "message": "Úp 1k acc.", "response": "A", "reply": "hú hú."},
    {"sender": "A", "message": "Oppa đu đỉnh k.", "response": "B", "reply": "dạo này bận săn sale quá."},
    {"sender": "B", "message": "có có.", "response": "A", "reply": "đu làm thanh khoản cho ae."},
    {"sender": "A", "message": "Thì vào team làm thanh khoản.", "response": "B", "reply": "ksao e a còn muốn giảm về 18 cơ. tích luỹ nhiều bứt phá càng mạnh."},
    {"sender": "B", "message": "Szybki KYC 20$ . 5 min.", "response": "A", "reply": "Về 18 rồi a ơi."},
    {"sender": "A", "message": "Múc thôi.", "response": "B", "reply": "Start."},
    {"sender": "B", "message": "Mấy anh em đẹp trai cho em xin 1 ref với.", "response": "A", "reply": "múc liên tục."},
    {"sender": "A", "message": "Mé hôm trc lên 25 e ko cắt. Cứ để đó nó xuống 18.", "response": "B", "reply": "Hôm đó mà cắt thì vào lại 18 ngon vãi."},
    {"sender": "B", "message": "Bao nhiêu vòng rồi. Số ko giàu dc.", "response": "A", "reply": "số thôi bảo r vẫn có điều chỉnh nhẹ, lại hồi ngay ý mà."},
    {"sender": "A", "message": "Chốt lời mà còn khó hơn gồng lỗ.", "response": "B", "reply": "Để hỏi trên nhóm xem có ko."},
    {"sender": "B", "message": "Síp hỏi giúp em với. Càng sớm càng tốt ạ.", "response": "A", "reply": "Số lương bao nhiêu thế."},
    {"sender": "A", "message": "Em mới out nên reff chậm.", "response": "B", "reply": "Ok để hỏi xem có ai ko."},
    {"sender": "B", "message": "Cái đó có vẻ ít.", "response": "A", "reply": "Lần đầu em làm nhiều thế."},
    {"sender": "A", "message": "Link nào để nó tính giá.", "response": "B", "reply": "Ib trực tiếp em nói gửi luôn được k síp."},
    {"sender": "B", "message": "Thế để xin tele rồi e nhắn nhé.", "response": "A", "reply": "Anh em nào có chơi con ocean bên sui ko."},
    {"sender": "A", "message": "Cái nhiệm vụ create meme anh em ai làm rồi chỉ tôi với.", "response": "B", "reply": "hê lô các con zời."},
    {"sender": "B", "message": "Game hệ TRON (TRX). Giữ 30 giây đc 0.25$. Ổn áp. May mắn sẽ thắng 1 chiếc Tesla. Xem bio nhé game này oker đó.", "response": "A", "reply": "ủa má pig trả r à quên mé luôn."},
    {"sender": "A", "message": "mấy nay bận quá k để ý. h vào thấy 0.003.", "response": "B", "reply": "nào thế e."},
    {"sender": "B", "message": "hnay tiếc chưa e.", "response": "A", "reply": "chốt mất r à."},
    {"sender": "A", "message": "E vẫn còn.", "response": "B", "reply": "Tại hôm qua đang lãi 1k6 mà quay đi cái nó tụt còn 1k nên thấy hoang mang. Sáng ra nó lại hồi lại rồi a."},
    {"sender": "B", "message": "Mé lãi gì cả ngàn đô thế.", "response": "A", "reply": "hâhhaha tăng ác vcc."},
    {"sender": "A", "message": "n sẽ điều chỉnh nhẹ mà.", "response": "B", "reply": "bh cứ thế tăng thôi."},
    {"sender": "B", "message": "kkkk.", "response": "A", "reply": "ông bạn a từ 5k lên 10k cmnr."},
    {"sender": "A", "message": "Ghê vãi ò. Nó cứ lên xuống ngon mà e toàn bị bất ngờ.", "response": "B", "reply": "Ko mua thêm dc nên ko dc bao nhiêu."},
    {"sender": "B", "message": "thôi giờ mua gì nữa.", "response": "A", "reply": "giữ đấy thôi."},
    {"sender": "A", "message": "n còn lên nữa.", "response": "B", "reply": "list coin base vs robinhood."},
    {"sender": "B", "message": "thì thôi kp nghĩ.", "response": "A", "reply": "Chắc bán thôi a."},
    {"sender": "A", "message": "Chọn 0.000023 rồi.", "response": "B", "reply": "no no e ơi."},
    {"sender": "B", "message": "nghe a.", "response": "A", "reply": "để đầu 5 thì bán."},
    {"sender": "A", "message": "nếu sợ thì đầu 4 thôi.", "response": "B", "reply": "k e cash out 50% cx đc."},
    {"sender": "A", "message": "Cắt bớt lấy tiền mua lại a ơi.", "response": "B", "reply": "Chứ e mua từ 0.000009."},
    {"sender": "B", "message": "Giờ x2.5 rồi.", "response": "A", "reply": "thích thì e cắt cx đc."},
    {"sender": "A", "message": "nhưng a nghĩ chả có điểm vào lại đâu.", "response": "B", "reply": "khó."},
    {"sender": "B", "message": "mua từ giá nào mà ghê v.", "response": "A", "reply": "cứ để thôi."},
    {"sender": "A", "message": "còn lên nữa.", "response": "B", "reply": "E x50."},
    {"sender": "B", "message": "Nên nhanh.", "response": "A", "reply": "à."},
    {"sender": "A", "message": "ra thế.", "response": "B", "reply": "Phải thế mới lẹ a à."},
    {"sender": "B", "message": "a để thấp quá.", "response": "A", "reply": "Lần trước ô trumb làm e cháy mất ít."},
    {"sender": "A", "message": "nảy chậm vcđ.", "response": "B", "reply": "Giờ cũng là ô trumb e lấy lại."},
    {"sender": "B", "message": "Mạnh mẽ lên a.", "response": "A", "reply": "Dc thì bú ko dc thì bay 1 chút."},
    {"sender": "A", "message": "Nay có gì mà bay ác.", "response": "B", "reply": "Btc gần 90k."},
    {"sender": "B", "message": "tối DCA thêm vào.", "response": "A", "reply": "chỉnh lại."},
    {"sender": "A", "message": "tối lợn trả tiền.", "response": "B", "reply": "lại có tiền DCA."},
    {"sender": "B", "message": "Đủ bữa nhậu ko.", "response": "A", "reply": "Kkk."},
    {"sender": "A", "message": "khéo chả đủ hộp sữa cho con.", "response": "B", "reply": "@@!"},
    {"sender": "B", "message": "k đủ quẳng vào thị trường tiếp.", "response": "A", "reply": "Hi."},
    {"sender": "A", "message": "Vãi ò biết vậy nãy bán luôn.", "response": "B", "reply": "Giờ lại tụt hơn 200u."},
    {"sender": "B", "message": "Chán vãi ò.", "response": "A", "reply": "hhahha."},
    {"sender": "A", "message": "đừng lo lắng e.", "response": "B", "reply": "nếu tối nay chạm 16 thì để."},
    {"sender": "B", "message": "k thì bán.", "response": "A", "reply": "Mé bận có 1 tí mà giảm ghê v."},
    {"sender": "A", "message": "Chốt rồi mua lại ngon hơn a ơi.", "response": "B", "reply": "Hye."},
    {"sender": "B", "message": "Nhưng chắc cũng phải chạm 90k mới quay đầu dc.", "response": "A", "reply": "Chắc rung tí thôi."},
    {"sender": "A", "message": "rung tý thôi.", "response": "B", "reply": "kệ."},
    {"sender": "B", "message": "mấy jo list nhỉ ae.", "response": "A", "reply": "vào chưa thấy j."},
    {"sender": "A", "message": "ae canh để cả hết hả, ai hold ko, btc đang bay.", "response": "B", "reply": "chuẩn bị quất ae."},
    {"sender": "B", "message": "Giá cao.", "response": "A", "reply": "kakaak, cao thì fai nhanh tay xả hết bác."},
    {"sender": "A", "message": "Chuẩn bị nào ae ơi.", "response": "B", "reply": "Ai nhanh tay dc giá cao."},
    {"sender": "B", "message": "Ai chậm tay giá thấp.", "response": "A", "reply": "kakakaka."},
    {"sender": "A", "message": "zô bú.", "response": "B", "reply": "0.007"},
    {"sender": "A", "message": "nãy fomo chơi tí, giờ ngồi chờ hồi thôi.", "response": "B", "reply": "@Congminhf, phong bạc không? Gửi lên phong bạc chơi cho vui."},
    {"sender": "B", "message": "nằm im đợi bú thôi em. kkk. không nhanh là mất cơ hội.", "response": "A", "reply": "oke anh. ARTFI cũng 100$ =))."},
    {"sender": "A", "message": "má rải mỗi con 100$. em vẫn hold mà, không biết bao giờ hồi.", "response": "B", "reply": "có gì chat ở đây cho vui. con lỏ Lescos bay kia mà scam vl mẹ nó."},
    {"sender": "B", "message": "thôi bỏ qua, thành khoản haha. chắc chẳng làm được gì hơn.", "response": "A", "reply": "má nó cay. mất 20u. thôi dca ARTFI, cố gỡ lại ít."},
    {"sender": "A", "message": "má để avatar gr chill vậy à? làm cho thấy thoải mái hơn à?", "response": "B", "reply": "kkk. chill mà, giờ ôm thì phải kiên nhẫn thôi."},
    {"sender": "B", "message": "mà con Pepe anh nhắc hồi nãy có vẻ lên được rồi. đánh giá sao?", "response": "A", "reply": "em thấy ổn, chắc hồi thêm chút nữa thì cân nhắc chốt."},
    {"sender": "A", "message": "anh nghĩ nên giữ lâu không? hay chốt sớm để dca tiếp?", "response": "B", "reply": "tùy, nhưng anh nghĩ giữ thêm chút nữa. con này tiềm năng."},
    {"sender": "B", "message": "con OP của em thế nào rồi? đã thấy nhúc nhích chưa?", "response": "A", "reply": "vẫn nằm im, cay thật sự. đang tính giảm bớt để thêm vào meme hệ Sol."},
    {"sender": "A", "message": "có meme nào đang nổi không? gợi ý anh vài con đi.", "response": "B", "reply": "anh xem con LESTER đi, nhưng cẩn thận, đừng dồn quá nhiều vốn."},
    {"sender": "B", "message": "mấy hôm nay BTC cứ tăng giảm khó lường. hold lâu thì hơi mệt.", "response": "A", "reply": "đúng rồi, nhưng chắc tới cuối tuần sẽ có sóng. chờ thêm tí."},
    {"sender": "A", "message": "oke, để xem sao. tối nay thử thêm lệnh nhẹ BTC nhé?", "response": "B", "reply": "chốt đấy. nhớ giữ vốn an toàn. thắng được thì mời nhậu!"},
    {"sender": "B", "message": "ARTFI nghe đâu cuối tuần có event. em cân nhắc tham gia không?", "response": "A", "reply": "để em xem sao. nhưng chắc không all-in đâu, phải cẩn thận."},
    {"sender": "A", "message": "trend này vẫn giữ được lâu không? hay sắp hết nhiệt rồi?", "response": "B", "reply": "chưa biết, nhưng volume đang giảm, có lẽ chỉ vài hôm nữa thôi."},
    {"sender": "B", "message": "con Pepe lúc nãy ông chốt chưa? thấy hồi lại mạnh rồi đó.", "response": "A", "reply": "chưa, đang ngồi canh. nhưng chắc mai chốt để nhẹ đầu."},
    {"sender": "A", "message": "suy nghĩ kỹ nhé. vì pump kiểu này dễ bị xả lắm.", "response": "B", "reply": "oke, cảm ơn ông. để tôi xem lại chart đã."},
    {"sender": "B", "message": "anh em trong nhóm kêu làm thêm task ARB. ông thử chưa?", "response": "A", "reply": "chưa, nhưng nghe bảo dễ làm. chắc tối nay test luôn."},
    {"sender": "A", "message": "test đi. biết đâu kiếm được ít token rồi hold lâu dài.", "response": "B", "reply": "vâng, giờ kiếm cái gì an toàn cũng tốt hơn là fomo."}
]

conversation_script_2 = [
    {"sender": "A", "message": "Thứ khỏe rồi đi thôi.", "response": "B", "reply": "được bro, chỗ nào vip vậy?"},
    {"sender": "B", "message": "Đi cả ngày ko update anh em ơi.", "response": "A", "reply": "tải app về chưa? liên kết acc trên web chưa?"},
    {"sender": "A", "message": "Rồi ad, hôm qua đi thì đc hôm nay ko thấy update.", "response": "C", "reply": "vào web liên kết lại phát nữa. trên andiroi update chậm lắm."},
    {"sender": "C", "message": "chứ iphone cái 1 à.", "response": "A", "reply": "sida quá."},
    {"sender": "A", "message": "đc rồi.", "response": "B", "reply": "thank ad."},
    {"sender": "B", "message": "xếp hạng mấy vậy?", "response": "C", "reply": "500 rồi, xong 17 game, đang join 25 game."},
    {"sender": "C", "message": "nốt đi.", "response": "A", "reply": "15 nhiệm vụ đa dạng dễ dàng hoàn thành cho trader mới."},
    {"sender": "A", "message": "nhanh tay tham gia, phần thưởng giá trị cho người đầu tiên!", "response": "B", "reply": "cũng định làm mà SH250i k có bằng đi."},
    {"sender": "B", "message": "Base. Clank coin. Vào xổ số x5 ae ơi.", "response": "C", "reply": "kiếm lambo thôi thầy!"},
    {"sender": "C", "message": "Vậy mình người dùng cũ. Chim cút khỏi okx à?", "response": "A", "reply": "xem lambo chia nát."},
    {"sender": "A", "message": "E xin link vô mua a ơi.", "response": "B", "reply": "Nhanh ko dowtrend."},
    {"sender": "B", "message": "Sol bay ác thế mà bags k nổ đi còn chờ đợi gì nữa nhở.", "response": "C", "reply": "Sâu giá này thì mua về lm gì nhỉ."},
    {"sender": "C", "message": "Xổ số ae, min x2.", "response": "A", "reply": "ern lv35 max đk 13k. Thế mua sâu 15k vêd lm mẹ gì nhỉ."},
    {"sender": "A", "message": "Dc hoàn thêm 0.007 sui.", "response": "B", "reply": "x4 LOL!"},
    {"sender": "B", "message": "Bú ác.", "response": "C", "reply": "bào kiểu này rồi ko ai chơi lại khóc."},
    {"sender": "C", "message": "Mua sâu cúng hay làm gì má?", "response": "A", "reply": "Clm đen rồi ngày đầu chạy lại đau mắt cá chân."},
    {"sender": "A", "message": "Thôi toang 6 ngày còn lại r.", "response": "B", "reply": "Sao cno nhận đc."},
    {"sender": "B", "message": "Mà mình ko nhận đc nhỉ.", "response": "C", "reply": "bro join đc game này k."},
    {"sender": "C", "message": "Ko join đc nên mới hỏi.", "response": "A", "reply": "Dễ gì mà lên đ thế."},
    {"sender": "A", "message": "Lên vững chứ ko phải giật.", "response": "B", "reply": "nhanh hay chậm gì cũng chắc hết."},
    {"sender": "B", "message": "Công nhận.", "response": "C", "reply": "anh em mua stake di ido."},
    {"sender": "C", "message": "Sắp bay tới nơi.", "response": "A", "reply": "Giờ stake là đẹp."},
    {"sender": "A", "message": "come and arrest me.", "response": "B", "reply": "clm."},
    {"sender": "B", "message": "lắm ng tây vậy.", "response": "C", "reply": "Để xem."},
    {"sender": "C", "message": "Ese làm gì tiếp theo.", "response": "A", "reply": "Dạo này nhiều sự kiện quá."},
    {"sender": "A", "message": "Đúng r.", "response": "B", "reply": "Càng ngày càng có niềm tin."},
    {"sender": "B", "message": "Lại càng có động lực.", "response": "C", "reply": "Để chờ thêm."},
    {"sender": "C", "message": "Chứ gì nữa.", "response": "A", "reply": "chăm vay."},
    {"sender": "A", "message": "Đù.", "response": "B", "reply": "Éo ai được quà rồi."},
    {"sender": "B", "message": "Ese sắp list thêm CEX tier 1.", "response": "C", "reply": "Chuẩn bị bung lụa tiếp nhoá."},
    {"sender": "C", "message": "Oh.", "response": "A", "reply": "Tier 1 chắc binance."},
    {"sender": "A", "message": "gn.", "response": "B", "reply": "gud moning."},
    {"sender": "B", "message": "trường chào tân tráy quá.", "response": "C", "reply": "xem voi."},
    {"sender": "C", "message": "có ai the.", "response": "A", "reply": "Bigdaddy Emily sir."},
    {"sender": "A", "message": "cháy nhất Bắc Từ Liêm.", "response": "B", "reply": "có hát ko thầy."},
    {"sender": "B", "message": "soon sir.", "response": "C", "reply": "Bú ko."},
    {"sender": "C", "message": "Chart đẹp vl.", "response": "A", "reply": "trend depin."},
    {"sender": "A", "message": "Giờ lại tụt hơn 200u.", "response": "B", "reply": "Chán vãi ò."},
    {"sender": "B", "message": "Chơi dài hơi thế này mệt quá.", "response": "A", "reply": "Đúng rồi, lúc nào cũng phải canh chừng."},
    {"sender": "A", "message": "Thôi để hôm nào lên lại cắt lỗ vậy.", "response": "B", "reply": "Cắt lỗ lúc nào cũng khó, nhưng biết đâu lại đúng thời điểm."},
    {"sender": "B", "message": "Vậy thì phải theo dõi liên tục thôi.", "response": "A", "reply": "Ừ, không theo dõi thì dễ bị bất ngờ."},
    {"sender": "A", "message": "Cứ tưởng lúc này sẽ ổn, ai ngờ lại tụt sâu.", "response": "B", "reply": "Cái này là cái khó của thị trường, không có gì là chắc chắn."},
    {"sender": "B", "message": "Chơi thì phải có lúc thắng lúc thua, quan trọng là chốt lời đúng lúc.", "response": "A", "reply": "Chắc phải học cách bình tĩnh thôi."},
    {"sender": "A", "message": "Ừ, từ từ rồi sẽ quen thôi.", "response": "B", "reply": "Đúng rồi, có kinh nghiệm rồi sẽ biết khi nào nên vào, khi nào nên ra."},
    {"sender": "A", "message": "Chắc phải nghiên cứu thêm vài dự án mới.", "response": "B", "reply": "Cái này đúng, phải đa dạng danh mục đầu tư."},
    {"sender": "B", "message": "Đầu tư dài hạn thì phải có chiến lược rõ ràng.", "response": "A", "reply": "Ừ, cứ phải có kế hoạch thì mới dễ thắng."},
    {"sender": "A", "message": "Lại còn phải tìm hiểu từng đồng coin nữa chứ.", "response": "B", "reply": "Khó thật đấy, phải làm nghiên cứu kỹ càng."},
    {"sender": "B", "message": "Dù sao thì đầu tư luôn là một cuộc chơi dài hơi.", "response": "A", "reply": "Chắc phải tiếp tục học hỏi thêm thôi."},
    {"sender": "A", "message": "Ừ, không học hỏi thì dễ bị thất bại." , "response": "B", "reply": "Cứ thử rồi rút kinh nghiệm thôi."},
    {"sender": "B", "message": "Chắc sắp tới phải làm vài chiến lược mới.", "response": "A", "reply": "Làm đi, để xem có hiệu quả không."},
    {"sender": "A", "message": "Cũng có thể phải điều chỉnh chiến thuật lại nữa.", "response": "B", "reply": "Chắc chắn rồi, không thể cứ đi theo một cách mãi được."},
    {"sender": "B", "message": "Vậy thì cứ làm thôi, đâu có gì phải lo." , "response": "A", "reply": "Đúng, cứ thử rồi sẽ biết."},
    {"sender": "A", "message": "Vậy thôi, chờ cơ hội tiếp theo thôi." , "response": "B", "reply": "Chờ cơ hội là điều quan trọng, ai cũng cần kiên nhẫn."},
    {"sender": "C", "message": "Con Pepe anh nhắc hồi nãy lên mạnh rồi, có vẻ tốt đấy.", "response": "A", "reply": "Đang canh thêm một chút nữa, nhưng chắc mai chốt để nhẹ đầu."},
    {"sender": "A", "message": "Anh nghĩ nên giữ lâu không? Hay chốt để dca tiếp?", "response": "B", "reply": "Tùy, nhưng anh nghĩ giữ thêm chút. Con này còn tiềm năng."},
    {"sender": "B", "message": "Con OP của em thế nào rồi? Đã thấy nhúc nhích chưa?", "response": "C", "reply": "Vẫn nằm im, cay thật sự. Đang tính giảm bớt để thêm vào meme hệ Sol."},
    {"sender": "C", "message": "Có meme nào đang nổi không? Gợi ý anh vài con đi.", "response": "A", "reply": "Anh xem con LESTER đi, nhưng đừng dồn quá nhiều vốn."},
    {"sender": "A", "message": "Mấy hôm nay BTC cứ tăng giảm khó lường. Hold lâu thì hơi mệt.", "response": "B", "reply": "Đúng rồi, nhưng chắc cuối tuần có sóng. Chờ thêm tí."},
    {"sender": "B", "message": "Tối nay thử thêm lệnh nhẹ BTC không?", "response": "C", "reply": "Chốt đấy. Nhớ giữ vốn an toàn. Thắng được thì mời nhậu!"},
    {"sender": "C", "message": "ARTFI nghe đâu cuối tuần có event. Anh định tham gia không?", "response": "A", "reply": "Để xem sao, chắc không all-in đâu. Phải cẩn thận."},
    {"sender": "A", "message": "Trend này còn giữ được lâu không? Hay sắp hết nhiệt rồi?", "response": "B", "reply": "Chưa biết, nhưng volume giảm, có lẽ chỉ vài hôm nữa thôi."},
    {"sender": "B", "message": "Con Pepe lúc nãy ông chốt chưa? Hồi lại mạnh rồi đấy.", "response": "C", "reply": "Chưa, đang ngồi canh. Nhưng chắc mai chốt để nhẹ đầu."},
    {"sender": "C", "message": "Suy nghĩ kỹ nhé. Pump kiểu này dễ bị xả lắm.", "response": "A", "reply": "Oke, cảm ơn ông. Để tôi xem lại chart đã."},
    {"sender": "A", "message": "Anh em trong nhóm kêu làm thêm task ARB. Ông thử chưa?", "response": "B", "reply": "Chưa, nhưng nghe bảo dễ làm. Chắc tối nay test luôn."},
    {"sender": "B", "message": "Test đi, biết đâu kiếm ít token rồi hold lâu dài.", "response": "C", "reply": "Vâng, giờ kiếm gì an toàn cũng tốt hơn là fomo."},
    {"sender": "C", "message": "Con Sui dạo này có event gì không? Thấy mọi người nhắc.", "response": "A", "reply": "Hình như đang có airdrop, nhưng phải check kỹ hơn."},
    {"sender": "A", "message": "Anh thấy con nào đang hot nữa không? Muốn thử thêm.", "response": "B", "reply": "Con Base Ecosystem đó, nghe nói có airdrop khá ổn."},
    {"sender": "B", "message": "Nhưng mà cũng đừng ham quá, cái gì cũng có rủi ro.", "response": "C", "reply": "Đúng rồi, phải quản lý vốn cho cẩn thận."},
    {"sender": "C", "message": "Chắc tối nay làm ít nhiệm vụ ARB nữa.", "response": "A", "reply": "Làm đi, ARB dễ farm mà cũng tiềm năng."},
    {"sender": "A", "message": "Chốt lời con Pepe chưa ông? Hay vẫn giữ?", "response": "B", "reply": "Vẫn giữ, đang đợi thêm chút nữa."},
    {"sender": "B", "message": "Nhưng mà pump kiểu này cũng hơi sợ, dễ xả bất ngờ.", "response": "C", "reply": "Đúng, cái gì nhiều volume quá cũng rủi ro cao."},
    {"sender": "C", "message": "BTC tuần này chắc sẽ có điều chỉnh nhẹ.", "response": "A", "reply": "Hy vọng thế, để còn DCA thêm."},
    {"sender": "A", "message": "Kế hoạch của ông sắp tới là gì?", "response": "B", "reply": "Chắc tập trung thêm vào các meme có tiềm năng."},
    {"sender": "B", "message": "Còn ông? Định làm gì tiếp?", "response": "C", "reply": "Tôi chắc đi farm ARB với thử vận may meme Sol."},
    {"sender": "A", "message": "Để coi tuần này còn con nào lên sóng không, nếu có thì gia tăng thêm.", "response": "B", "reply": "Nhìn xem volume các meme, nếu nhiều thì có thể thử thêm."},
    {"sender": "B", "message": "Lúc nào cũng phải chú ý cái volume, quan trọng đấy.", "response": "C", "reply": "Đúng rồi, thị trường này hay bị bơm xong xả lắm."},
    {"sender": "C", "message": "Con ARB hiện giờ ổn không? Hay lại có thể có biến?", "response": "A", "reply": "Chắc ổn, nhưng đừng quá kỳ vọng. Cẩn thận."},
    {"sender": "A", "message": "Chắc tôi giữ nguyên ARB và tiếp tục theo dõi BTC thôi. Còn ông?", "response": "B", "reply": "Tôi nghĩ thêm vào meme một chút nữa, ít thôi."},
    {"sender": "B", "message": "Mấy con meme thật sự cũng mệt, lên xuống thất thường. Nhưng mà cũng kiếm được kha khá.", "response": "C", "reply": "Kiếm được là mừng rồi, nhưng phải biết dừng đúng lúc."},
    {"sender": "C", "message": "Ai mà không thích kiếm nhanh, nhưng phải tính toán chứ.", "response": "A", "reply": "Đúng rồi, phải biết khi nào cắt lỗ, khi nào chốt lời."},
    {"sender": "A", "message": "Thấy mấy người trong nhóm thử làm thêm game ARB, ông có thử không?", "response": "B", "reply": "Chưa thử, nhưng thấy bảo dễ mà."},
    {"sender": "C", "message": "Thời gian này có vẻ sắp có sóng ARB, mọi người để ý nhé.", "response": "A", "reply": "Sẽ theo dõi, nếu có dấu hiệu tăng thì tôi nhảy vào."},
    {"sender": "A", "message": "Ông làm ARB có vui không? Lợi nhuận sao?", "response": "B", "reply": "Cũng vui, lợi nhuận thì có, nhưng phải chăm chỉ."},
    {"sender": "C", "message": "Tôi đang định thử thêm một chút ARB, có lẽ tuần này làm thử một đợt nữa.", "response": "A", "reply": "Tốt, nhưng nhớ giữ vốn an toàn nhé."},
    {"sender": "A", "message": "Vẫn còn con nào có tiềm năng giống Pepe không?", "response": "B", "reply": "Có thể là con MAGA hoặc PUNK, nhưng không dám chắc."},
    {"sender": "C", "message": "Anh em cứ giữ tinh thần lạc quan, thị trường này hay thay đổi lắm.", "response": "A", "reply": "Đúng, phải giữ đầu lạnh."},
    {"sender": "A", "message": "Tuần này có ai nghĩ BTC sẽ có điều chỉnh không?", "response": "B", "reply": "Có thể, tôi dự đoán sẽ có điều chỉnh nhẹ trước khi tăng lại."},
    {"sender": "B", "message": "Điều chỉnh nhẹ là cơ hội để dca vào thêm.", "response": "C", "reply": "Đúng, nhưng phải có kế hoạch rõ ràng."},
    {"sender": "C", "message": "Tối nay có thời gian làm thêm ARB không? Tôi đang có một vài lệnh nhẹ.", "response": "A", "reply": "Có, tôi cũng đang muốn thử xem sao."},
    {"sender": "A", "message": "Anh em thử chia sẻ một số chiến lược làm ARB xem.", "response": "B", "reply": "Tôi hay làm theo phản ứng của thị trường, volume lớn là vào, volume giảm thì thoát."},
    {"sender": "A", "message": "Có con meme nào mà anh em đang giữ lâu không?", "response": "B", "reply": "Có, tôi vẫn giữ con DOGE. Nó không nhanh nhưng ổn định."},
    {"sender": "A", "message": "Hệ Solana có tiềm năng đó, nhưng phải kiểm tra kỹ xem có sự kiện nào lớn không đã.", "response": "B", "reply": "Đúng, cần phải theo dõi."},
    {"sender": "A", "message": "Cảm ơn mọi người, giờ tôi tiếp tục xem lại chart và lên kế hoạch cho tuần này.", "response": "B", "reply": "Ok, giữ vững tinh thần nhé!"},
    {"sender": "A", "message": "Tuần này BTC có vẻ đã bắt đầu có dấu hiệu hồi phục, có ai còn giữ lâu dài không?", "response": "B", "reply": "Tôi vẫn giữ một phần, đang cân nhắc việc chốt lời nếu lên cao."},
    {"sender": "B", "message": "Cái chính là canh được điểm vào và ra hợp lý, phải có kế hoạch từ trước.", "response": "C", "reply": "Đúng vậy, nhiều khi thị trường lên rồi xuống nhanh quá, phải tính toán."},
    {"sender": "C", "message": "Cảm giác gần đây thị trường khá tĩnh lặng, ít biến động lớn. Không biết có phải do mọi người đang đợi điều gì đó không?", "response": "A", "reply": "Có thể đấy, cũng có thể là mọi người đang chờ đợt sóng mới."},
    {"sender": "A", "message": "Bên ngoài có tin tức gì về các quốc gia lớn thay đổi chính sách tiền tệ không?", "response": "B", "reply": "Cứ mỗi lần có tin về việc tăng lãi suất là BTC hay bị ảnh hưởng. Có thể là yếu tố này."},
    {"sender": "B", "message": "Cẩn thận với các chính sách của Fed, nếu họ tăng lãi suất, BTC có thể sẽ điều chỉnh tiếp.", "response": "C", "reply": "Đúng rồi, các động thái của các ngân hàng trung ương rất quan trọng."},
    {"sender": "C", "message": "Thị trường luôn chịu ảnh hưởng từ những tin tức này. Thêm nữa là dòng tiền từ các quỹ lớn có thể vào bất cứ lúc nào.", "response": "A", "reply": "Đúng, mỗi đợt có tin lớn là một cơ hội mới. Phải chú ý vào dòng tiền."},
    {"sender": "A", "message": "Chắc tôi sẽ vào thêm một chút nếu có điều chỉnh nhẹ. Còn ông B?", "response": "B", "reply": "Tôi cũng vậy, có thể thêm một ít vào những lúc điều chỉnh."},
    {"sender": "B", "message": "Lần này tôi định vào ETH thay vì BTC, nó có vẻ có nhiều sự kiện phát triển trong năm nay.", "response": "C", "reply": "ETH là sự lựa chọn tốt, nhưng cũng phải chú ý đến việc cạnh tranh từ các blockchain khác."},
    {"sender": "A", "message": "Solana cũng đang lên, tuần này thấy có vài tin tức tốt. Còn ARB, mọi người vẫn theo dõi không?", "response": "B", "reply": "Tôi vẫn theo dõi ARB, nhưng cảm giác là thị trường ARB đang hơi bão hòa."},
    {"sender": "B", "message": "Có thể, nhưng dòng tiền vào vẫn lớn, có thể sẽ có những đợt sóng mới.", "response": "C", "reply": "Không thể nói trước được, nhưng chắc chắn sẽ có những đợt xả mạnh."},
    {"sender": "A", "message": "Bình tĩnh, đừng quá vội vàng. Cứ theo dõi thị trường rồi quyết định sau.", "response": "B", "reply": "Đúng, quyết định đúng lúc thì không bao giờ sai."},
    {"sender": "B", "message": "Nhớ giữ vững kỷ luật, không để cảm xúc chi phối, đó là cách giữ vững được lợi nhuận dài hạn.", "response": "C", "reply": "Tôi sẽ lưu ý, cảm xúc mà không kiểm soát được thì dễ thua lỗ."},
    {"sender": "C", "message": "Anh em còn muốn thêm con nào vào danh mục không? Tối nay tôi có thời gian rà soát một lượt.", "response": "A", "reply": "Có thể thêm một chút vào ARB, nhưng tôi sẽ kiểm tra kỹ trước khi quyết định."},
    {"sender": "A", "message": "Nói chung là phải chuẩn bị tinh thần cho mọi tình huống. Thị trường crypto thay đổi từng ngày.", "response": "B", "reply": "Đúng vậy, khi nào cảm thấy không an toàn thì phải rút lui."},
    {"sender": "B", "message": "Anh em có muốn thử thêm cái mới không? Tôi thấy có vài token mới ra mắt, có vẻ khá tiềm năng.", "response": "C", "reply": "Mới ra mắt thì cũng phải nghiên cứu kỹ, không phải cái gì mới cũng đáng đầu tư."},
    {"sender": "A", "message": "Tôi nghĩ tuần này sẽ có nhiều biến động, hãy chuẩn bị tinh thần tốt để đón nhận mọi cơ hội.", "response": "B", "reply": "Cảm ơn các bạn, mình sẽ xem xét và chia vốn hợp lý."},
    {"sender": "B", "message": "Cảm ơn mọi người, tuần này chắc chắn sẽ có nhiều điều thú vị!", "response": "C", "reply": "Chúc anh em đầu tư thành công, chúng ta sẽ tiếp tục theo dõi!"},
    {"sender": "A", "message": "Có ai để ý thấy con MAGA pump mạnh sáng nay không?", "response": "B", "reply": "Có, nhưng tôi nghĩ nó chỉ pump ngắn hạn, xả ngay thì hơn."},
    {"sender": "B", "message": "Mấy con kiểu này chỉ fomo là chính, ông có nhảy vào không?", "response": "C", "reply": "Tôi có mua một ít, đang canh để xả, sợ bị kẹt."},
    {"sender": "C", "message": "Con MAGA này có gì đặc biệt không? Hay chỉ là hiệu ứng fomo?", "response": "A", "reply": "Chủ yếu là fomo, nhưng cũng có team làm marketing khá mạnh."},
    {"sender": "A", "message": "Mà ông thấy meme dạo này sao? Có vẻ thị trường meme đang bão hòa.", "response": "B", "reply": "Đúng, nhưng vẫn có con nổi bật nếu biết chọn lọc. Ví dụ như Pepe tuần trước."},
    {"sender": "B", "message": "Pepe mà ông chốt lời kịp thì ngon. Tôi thấy nó đang tụt lại rồi.", "response": "C", "reply": "Ừ, đúng là lúc nào cũng phải theo sát."},
    {"sender": "C", "message": "Anh em có coin nào để hold lâu dài không? Hay toàn chơi sóng ngắn?", "response": "A", "reply": "Tôi giữ ETH và BTC lâu dài, còn lại thì chỉ chơi ngắn hạn."},
    {"sender": "A", "message": "Solana dạo này cũng ổn, có vẻ đang phục hồi sau một thời gian điều chỉnh.", "response": "B", "reply": "Solana đúng là đáng chú ý, nhưng phải xem thêm các dự án trên đó nữa."},
    {"sender": "B", "message": "Nhắc đến Solana, tôi thấy có dự án Serum mới công bố roadmap, nghe khá thú vị.", "response": "C", "reply": "Serum thì lâu rồi, nhưng roadmap mới có thể thu hút thêm dòng tiền."},
    {"sender": "C", "message": "Cái chính là xem cộng đồng của nó có mạnh không. Dự án nào cũng cần cộng đồng ủng hộ mới sống lâu được.", "response": "A", "reply": "Đúng, cộng đồng là yếu tố quyết định sự sống còn."},
    {"sender": "A", "message": "Nhắc tới cộng đồng, bên ARB đang có event gì đó, ông nào theo dõi không?", "response": "B", "reply": "Có, event nhiệm vụ. Dễ làm mà thưởng cũng ổn."},
    {"sender": "B", "message": "Tôi thấy event này thu hút nhiều người, nhưng không biết liệu sau khi kết thúc thì giá có bị xả mạnh không.", "response": "C", "reply": "Có thể, thường sau event là xả, nên tôi sẽ không giữ lâu."},
    {"sender": "C", "message": "Tôi cũng nghĩ vậy, nhưng vẫn sẽ làm nhiệm vụ để lấy phần thưởng.", "response": "A", "reply": "Đúng, phần thưởng thì không bỏ qua được, nhưng nên thoát sớm."},
    {"sender": "A", "message": "Mấy ông có quan tâm hệ Avalanche không? Tôi thấy nó có một vài dự án mới.", "response": "B", "reply": "Có, Avalanche cũng đáng theo dõi, nhưng phí gas hơi cao."},
    {"sender": "B", "message": "Dạo này Avalanche không còn quá nổi, nhưng nếu có dự án tốt thì vẫn đáng để ý.", "response": "C", "reply": "Đúng, tôi nghĩ Avalanche đang cố lấy lại vị thế."},
    {"sender": "C", "message": "Hệ Avalanche cần thêm nhiều dự án nổi bật để kéo cộng đồng quay lại.", "response": "A", "reply": "Đúng, nhưng tôi nghĩ vẫn có tiềm năng nếu họ phát triển đúng hướng."},
    {"sender": "A", "message": "Ông nào có chiến thuật gì mới cho tuần này không? Chia sẻ để học hỏi.", "response": "B", "reply": "Tôi nghĩ tập trung vào các dự án có sự kiện lớn sắp tới, thường là cơ hội tốt."},
    {"sender": "B", "message": "Ngoài ra, chia vốn nhỏ để giảm rủi ro. Đừng all-in vào một dự án.", "response": "C", "reply": "Tôi cũng đồng ý, all-in rủi ro cao lắm, dễ cháy tài khoản."},
    {"sender": "C", "message": "Tối nay tôi sẽ rà soát thêm một vài dự án mới, nếu thấy gì hay sẽ báo lại anh em.", "response": "A", "reply": "Ok, nhớ cập nhật nhé! Anh em cùng tiến."},
    {"sender": "A", "message": "Mấy ông có theo dõi thị trường NFT không? Tôi thấy nó đang im lặng hơn trước.", "response": "B", "reply": "NFT giờ khó chơi hơn, nhưng vẫn có một số dự án về game NFT đáng chú ý."},
    {"sender": "B", "message": "Cái chính là chọn đúng dự án, không thì dễ bị kẹt vốn.", "response": "C", "reply": "Tôi thì nghĩ NFT vẫn có tiềm năng, nhưng phải chờ thị trường hồi lại đã."},
    {"sender": "C", "message": "Nếu NFT game kết hợp với blockchain mạnh thì vẫn rất tiềm năng.", "response": "A", "reply": "Đúng, tôi cũng nghĩ vậy. Sẽ theo dõi thêm."},
    {"sender": "A", "message": "Ok anh em, tối nay cùng phân tích thêm thị trường nhé. Hẹn gặp lại!", "response": "B", "reply": "Chắc chắn rồi, hẹn gặp tối nay!"},
    {"sender": "A", "message": "Dạo này ông có để ý đến các stablecoin không? Mấy con mới có vẻ thú vị.", "response": "B", "reply": "Stablecoin thì ổn định thôi, nhưng có vài con mới cũng đáng để xem thử."},
    {"sender": "B", "message": "Mới có con GUSD, họ đang làm khá mạnh về việc tích hợp với các dự án DeFi lớn.", "response": "C", "reply": "Thị trường stablecoin không dễ xâm nhập, nhưng nếu có sự hỗ trợ từ các nền tảng lớn thì khả năng thành công cao."},
    {"sender": "C", "message": "Tôi thấy USDC vẫn đang chiếm ưu thế, nhưng sự cạnh tranh từ các stablecoin mới đang ngày càng gay gắt.", "response": "A", "reply": "Đúng, cạnh tranh tăng lên có thể khiến giá trị của USDC bị ảnh hưởng, cần theo dõi sát sao."},
    {"sender": "A", "message": "Thế ông có đồng nào đang dự định tăng tỷ trọng không? Để tôi tham khảo chút.", "response": "B", "reply": "Tôi đang xem xét tăng tỷ trọng vào LINK, có vẻ giá của nó sẽ tăng khi các dự án DeFi tiếp tục phát triển."},
    {"sender": "B", "message": "Chainlink có hợp đồng với nhiều đối tác lớn, khả năng vẫn còn room để phát triển. Nhưng cũng cần chờ đợi thêm tin tức mới.", "response": "C", "reply": "Nếu thế thì tôi cũng sẽ nghiên cứu thêm về LINK. Cảm ơn chia sẻ nhé."},
    {"sender": "C", "message": "Tôi cũng đang theo dõi AAVE và UNI, các dự án DeFi lâu dài. Dù thị trường đi lên hay xuống, chúng vẫn sẽ có tiềm năng nhất định.", "response": "A", "reply": "Cả hai con đó đều ổn, cộng đồng của chúng cũng mạnh. Chắc chắn sẽ có sự phục hồi khi thị trường ổn định."},
    {"sender": "A", "message": "Chắc phải thử nghiệm vào các dự án này. Thị trường DeFi có thể sẽ phục hồi mạnh mẽ khi có dòng tiền đổ vào lại.", "response": "B", "reply": "Chắc chắn rồi, DeFi vẫn là xu hướng dài hạn. Chúng ta phải kiên nhẫn."},
    {"sender": "B", "message": "Mà ông có để ý gì về việc các dự án bắt đầu chuyển hướng sang Web3 không? Tôi thấy xu hướng này đang nổi bật hơn.", "response": "C", "reply": "Web3 đang rất hot, nhưng tôi nghĩ cần thời gian để xây dựng cộng đồng và ứng dụng thực tế. Tuy nhiên, nếu thành công thì sẽ rất lớn."},
    {"sender": "C", "message": "Web3 là tương lai, nhưng cần xem liệu các dự án có thể thực hiện đúng những gì họ đã hứa không. Tiềm năng thì rất lớn.", "response": "A", "reply": "Đúng, điều quan trọng là cộng đồng và nhà phát triển có đủ khả năng thực hiện đúng chiến lược hay không."},
    {"sender": "A", "message": "Chắc chắn, nếu những dự án Web3 kết hợp tốt với DeFi và NFT thì sẽ tạo ra một hệ sinh thái vững mạnh.", "response": "B", "reply": "Tôi nghĩ vẫn còn thời gian để xem xét, nhưng không thể bỏ qua những dự án này."},
    {"sender": "B", "message": "Một số coin về Web3 đang dần hình thành mạng lưới riêng, có thể cạnh tranh với những ông lớn hiện tại. Phải cẩn thận không để bỏ lỡ.", "response": "C", "reply": "Tôi đồng ý, đừng bỏ qua bất kỳ cơ hội nào, nhưng cũng phải thận trọng với rủi ro."},
    {"sender": "C", "message": "Tối nay tôi sẽ dành thêm thời gian tìm hiểu về các dự án Web3, nếu thấy cái nào hay sẽ gửi cho anh em.", "response": "A", "reply": "Ok, chắc chắn rồi. Hãy cập nhật sớm nhé!"}, 
    {"sender": "A", "message": "Đúng rồi, theo dõi kỹ những thay đổi trong thị trường là rất quan trọng, nhất là những xu hướng mới như Web3.", "response": "B", "reply": "Đúng, đây sẽ là một hướng đi mới trong thời gian tới. Phải chuẩn bị kỹ."},
    {"sender": "B", "message": "Tôi nghe nói về một dự án Web3 mới sắp ra mắt, có vẻ sẽ là đối thủ đáng gờm. Chắc chắn sẽ có ảnh hưởng lớn.", "response": "C", "reply": "Cái này hay đấy, nếu có thêm thông tin thì chia sẻ cho anh em biết nhé!"}, 
    {"sender": "C", "message": "Sắp tới chắc sẽ có nhiều sự kiện Web3, chúng ta có thể theo dõi và tham gia vào các cộng đồng để hiểu rõ hơn về xu hướng này.", "response": "A", "reply": "Tôi sẽ tìm hiểu thêm. Web3 là một thị trường tiềm năng nhưng cũng cần nhiều sự đánh giá từ thực tế."},
    {"sender": "A", "message": "Tuần này có dự án nào sắp ra mắt không? Tôi muốn thử vận may với vài con mới.", "response": "B", "reply": "Có một dự án NFT gaming trên mạng lưới Solana, nghe nói đang khá hot."},
    {"sender": "B", "message": "Dự án tên là gì? Có link tham khảo không?", "response": "C", "reply": "Tôi nhớ là dự án tên Dawn of DeFi. Vẫn đang trong giai đoạn whitelist."},
    {"sender": "C", "message": "Mấy dự án gaming NFT thường cần thời gian để phát triển cộng đồng. Nếu vào thì xác định chờ lâu.", "response": "A", "reply": "Tôi ổn với việc chờ lâu, miễn là dự án có roadmap rõ ràng và đội ngũ uy tín."},
    {"sender": "A", "message": "Mọi người có để ý mấy dự án metaverse không? Dạo này hình như có dấu hiệu phục hồi.", "response": "B", "reply": "Metaverse vẫn là câu chuyện dài, nhưng các nền tảng lớn như Decentraland hay Sandbox đang dần thu hút lại sự chú ý."},
    {"sender": "B", "message": "Mấy dự án này trước đây hype kinh khủng, nhưng giờ phải xem liệu họ có thể phát triển thêm gì mới không.", "response": "C", "reply": "Đúng, hype thì dễ, nhưng phát triển thật sự và tạo ra giá trị mới là cái khó."},
    {"sender": "C", "message": "Metaverse mà kết hợp tốt với Web3 thì sẽ tạo ra một thị trường rất lớn. Chúng ta nên theo dõi.", "response": "A", "reply": "Tôi đồng ý. Nếu các dự án lớn như Sandbox có thêm ứng dụng thực tế thì chắc chắn sẽ hồi phục mạnh."},
    {"sender": "A", "message": "Tuần này có thông tin gì mới từ các blockchain lớn không? Ví dụ như Ethereum hay BNB Chain?", "response": "B", "reply": "Ethereum đang chuẩn bị nâng cấp tiếp, tập trung vào việc giảm phí giao dịch. Còn BNB thì mới tung ra một quỹ phát triển DeFi."},
    {"sender": "B", "message": "Cái quỹ này nghe nói sẽ hỗ trợ các dự án mới, có thể là cơ hội để tìm kiếm những token tiềm năng.", "response": "C", "reply": "Phải xem họ phân bổ thế nào. Nếu đầu tư đúng thì hệ sinh thái của BNB sẽ mạnh hơn rất nhiều."},
    {"sender": "C", "message": "Ngoài ra, hệ Polygon cũng đang có nhiều động thái tích cực, hợp tác với các thương hiệu lớn để mở rộng ứng dụng.", "response": "A", "reply": "Polygon đúng là đáng chú ý. Mấy dự án trên Polygon cũng có phí giao dịch rẻ, dễ tiếp cận hơn."},
    {"sender": "A", "message": "Mấy ông nghĩ sao về việc đầu tư vào stablecoin staking? An toàn nhưng lợi nhuận thấp.", "response": "B", "reply": "Nếu không thích rủi ro thì tốt, nhưng tôi thích chơi mạo hiểm hơn một chút."},
    {"sender": "B", "message": "Tuy nhiên, staking stablecoin có thể dùng để bảo toàn vốn khi thị trường điều chỉnh mạnh.", "response": "C", "reply": "Đúng, nó là lựa chọn an toàn, nhất là khi thị trường quá biến động."},
    {"sender": "C", "message": "Tôi thì chia ra, một phần staking stablecoin để giảm rủi ro, phần còn lại vào các dự án có tiềm năng cao hơn.", "response": "A", "reply": "Đó cũng là chiến lược tôi đang áp dụng. Phải đa dạng hóa danh mục đầu tư."},
    {"sender": "A", "message": "Tuần này chắc tôi sẽ dành thời gian theo dõi kỹ Polygon và BNB Chain. Còn ông thì sao?", "response": "B", "reply": "Tôi sẽ nghiên cứu thêm về các dự án trên Solana. Hệ này có vẻ đang phục hồi tốt."},
    {"sender": "B", "message": "Ngoài ra, tôi cũng đang tìm hiểu thêm về hệ Avalanche. Thị trường DeFi trên đó có vẻ sắp có động thái mới.", "response": "C", "reply": "Nếu ông có thông tin gì mới thì nhớ báo nhé. Tôi cũng đang cân nhắc Avalanche."},
    {"sender": "C", "message": "Tối nay anh em cập nhật thêm những tin tức mới để chuẩn bị cho tuần tới nhé.", "response": "A", "reply": "Chắc chắn rồi. Chúc anh em tuần này thắng lớn!"},
    {"sender": "A", "message": "Ok, để tối tôi tìm hiểu thêm vài con mới. Chúng ta cùng chia sẻ và quyết định sau.", "response": "B", "reply": "Đồng ý! Cùng nhau đi lên anh em!"},
    {"sender": "A", "message": "Tuần này có dự án nào sắp ra mắt không? Tôi muốn thử vận may với vài con mới.", "response": "B", "reply": "Có một dự án NFT gaming trên mạng lưới Solana, nghe nói đang khá hot."},
    {"sender": "B", "message": "Dự án tên là gì? Có link tham khảo không?", "response": "C", "reply": "Tôi nhớ là dự án tên Dawn of DeFi. Vẫn đang trong giai đoạn whitelist."},
    {"sender": "C", "message": "Mấy dự án gaming NFT thường cần thời gian để phát triển cộng đồng. Nếu vào thì xác định chờ lâu.", "response": "A", "reply": "Tôi ổn với việc chờ lâu, miễn là dự án có roadmap rõ ràng và đội ngũ uy tín."},
    {"sender": "A", "message": "Mọi người có để ý mấy dự án metaverse không? Dạo này hình như có dấu hiệu phục hồi.", "response": "B", "reply": "Metaverse vẫn là câu chuyện dài, nhưng các nền tảng lớn như Decentraland hay Sandbox đang dần thu hút lại sự chú ý."},
    {"sender": "B", "message": "Mấy dự án này trước đây hype kinh khủng, nhưng giờ phải xem liệu họ có thể phát triển thêm gì mới không.", "response": "C", "reply": "Đúng, hype thì dễ, nhưng phát triển thật sự và tạo ra giá trị mới là cái khó."},
    {"sender": "C", "message": "Metaverse mà kết hợp tốt với Web3 thì sẽ tạo ra một thị trường rất lớn. Chúng ta nên theo dõi.", "response": "A", "reply": "Tôi đồng ý. Nếu các dự án lớn như Sandbox có thêm ứng dụng thực tế thì chắc chắn sẽ hồi phục mạnh."},
    {"sender": "A", "message": "Tuần này có thông tin gì mới từ các blockchain lớn không? Ví dụ như Ethereum hay BNB Chain?", "response": "B", "reply": "Ethereum đang chuẩn bị nâng cấp tiếp, tập trung vào việc giảm phí giao dịch. Còn BNB thì mới tung ra một quỹ phát triển DeFi."},
    {"sender": "B", "message": "Cái quỹ này nghe nói sẽ hỗ trợ các dự án mới, có thể là cơ hội để tìm kiếm những token tiềm năng.", "response": "C", "reply": "Phải xem họ phân bổ thế nào. Nếu đầu tư đúng thì hệ sinh thái của BNB sẽ mạnh hơn rất nhiều."},
    {"sender": "C", "message": "Ngoài ra, hệ Polygon cũng đang có nhiều động thái tích cực, hợp tác với các thương hiệu lớn để mở rộng ứng dụng.", "response": "A", "reply": "Polygon đúng là đáng chú ý. Mấy dự án trên Polygon cũng có phí giao dịch rẻ, dễ tiếp cận hơn."},
    {"sender": "A", "message": "Mấy ông nghĩ sao về việc đầu tư vào stablecoin staking? An toàn nhưng lợi nhuận thấp.", "response": "B", "reply": "Nếu không thích rủi ro thì tốt, nhưng tôi thích chơi mạo hiểm hơn một chút."},
    {"sender": "B", "message": "Tuy nhiên, staking stablecoin có thể dùng để bảo toàn vốn khi thị trường điều chỉnh mạnh.", "response": "C", "reply": "Đúng, nó là lựa chọn an toàn, nhất là khi thị trường quá biến động."},
    {"sender": "C", "message": "Tôi thì chia ra, một phần staking stablecoin để giảm rủi ro, phần còn lại vào các dự án có tiềm năng cao hơn.", "response": "A", "reply": "Đó cũng là chiến lược tôi đang áp dụng. Phải đa dạng hóa danh mục đầu tư."},
    {"sender": "A", "message": "Tuần này chắc tôi sẽ dành thời gian theo dõi kỹ Polygon và BNB Chain. Còn ông thì sao?", "response": "B", "reply": "Tôi sẽ nghiên cứu thêm về các dự án trên Solana. Hệ này có vẻ đang phục hồi tốt."},
    {"sender": "B", "message": "Ngoài ra, tôi cũng đang tìm hiểu thêm về hệ Avalanche. Thị trường DeFi trên đó có vẻ sắp có động thái mới.", "response": "C", "reply": "Nếu ông có thông tin gì mới thì nhớ báo nhé. Tôi cũng đang cân nhắc Avalanche."},
    {"sender": "C", "message": "Tối nay anh em cập nhật thêm những tin tức mới để chuẩn bị cho tuần tới nhé.", "response": "A", "reply": "Chắc chắn rồi. Chúc anh em tuần này thắng lớn!"},
    {"sender": "A", "message": "Ok, để tối tôi tìm hiểu thêm vài con mới. Chúng ta cùng chia sẻ và quyết định sau.", "response": "B", "reply": "Đồng ý! Cùng nhau đi lên anh em!"},
    {"sender": "A", "message": "Mọi người có để ý đến việc chính phủ các nước ngày càng kiểm soát thị trường crypto không? Sẽ ảnh hưởng như thế nào đến các dự án Web3 và DeFi?", "response": "B", "reply": "Tôi nghĩ chính phủ kiểm soát là điều không tránh khỏi, nhất là khi thị trường phát triển quá nhanh. Nhưng cũng là cơ hội để những dự án minh bạch phát triển."},
    {"sender": "B", "message": "Những dự án tập trung vào việc tuân thủ luật pháp, như KYC và AML, sẽ có lợi thế trong dài hạn. DeFi sẽ phải thay đổi để thích nghi.", "response": "C", "reply": "Đúng rồi, nhưng điều này cũng có thể làm giảm tính phi tập trung của DeFi, vì nó mâu thuẫn với tinh thần ban đầu của blockchain."},
    {"sender": "C", "message": "Tôi nghĩ các dự án DeFi sẽ tìm cách cân bằng giữa việc tuân thủ quy định và duy trì tính phi tập trung. Nếu làm được, thị trường sẽ lớn mạnh hơn.", "response": "A", "reply": "Đúng vậy, nhưng điều đó không hề dễ. Sẽ cần những cải tiến lớn về công nghệ và sự hợp tác giữa các bên."},
    {"sender": "A", "message": "Có thể sẽ có một thế hệ blockchain mới ra đời, tập trung vào việc hỗ trợ các ứng dụng hợp pháp hóa mà vẫn giữ được tính phi tập trung.", "response": "B", "reply": "Điều đó rất khả thi. Những nền tảng như Ethereum hoặc Polkadot có thể đi đầu trong xu hướng này."},
    {"sender": "B", "message": "Mà ông nào đã thử trải nghiệm dự án mới trên Polkadot chưa? Hệ sinh thái này dạo gần đây có vẻ yên ắng hơn, nhưng vẫn có một số dự án tốt.", "response": "C", "reply": "Tôi có xem qua vài dự án parachain mới, nhưng chưa quyết định đầu tư. Polkadot vẫn là nền tảng mạnh, chỉ là chưa có sự kiện lớn gần đây."},
    {"sender": "C", "message": "Tôi nghĩ Polkadot đang chờ đợi một bước đột phá lớn. Nếu họ có thể làm được, thì hệ sinh thái này sẽ rất đáng chú ý.", "response": "A", "reply": "Đúng, tôi vẫn tin rằng Polkadot có tiềm năng lớn, nhưng cần thêm thời gian để các dự án trên nền tảng này phát triển mạnh hơn."},
    {"sender": "A", "message": "Mọi người nghĩ gì về Cardano? Tôi thấy cộng đồng vẫn rất mạnh, nhưng hệ sinh thái chưa có nhiều dự án nổi bật.", "response": "B", "reply": "Cardano là dự án lâu dài, họ rất kỹ lưỡng trong việc phát triển. Nhưng điều đó cũng làm họ chậm hơn các đối thủ."},
    {"sender": "B", "message": "Nếu Cardano có thể thu hút thêm các nhà phát triển và dự án lớn, thì nó sẽ có vị thế tốt hơn trong thị trường.", "response": "C", "reply": "Tôi đồng ý. Nhưng với tốc độ hiện tại, họ cần thêm thời gian để xây dựng một hệ sinh thái đủ hấp dẫn."},
    {"sender": "C", "message": "Dù sao, Cardano vẫn là một nền tảng ổn định. Với những người thích đầu tư dài hạn, đây có thể là lựa chọn an toàn hơn.", "response": "A", "reply": "Đúng. Tôi sẽ theo dõi thêm, đặc biệt là các dự án DeFi trên Cardano."},
    {"sender": "A", "message": "Nói về đầu tư dài hạn, mọi người có nghĩ stablecoin sẽ trở thành một phần quan trọng hơn trong các chiến lược không?", "response": "B", "reply": "Chắc chắn. Stablecoin mang lại sự ổn định trong một thị trường đầy biến động. Nó là công cụ quan trọng để bảo toàn vốn."},
    {"sender": "B", "message": "Ngoài ra, stablecoin cũng có thể được sử dụng rộng rãi hơn trong các ứng dụng thực tế, như thanh toán xuyên biên giới.", "response": "C", "reply": "Nhưng điều quan trọng là phải có sự minh bạch và kiểm toán rõ ràng. Nếu không, stablecoin có thể gây ra rủi ro lớn."},
    {"sender": "C", "message": "Tôi đồng ý. Những đồng như USDC hoặc DAI, với cơ chế minh bạch hơn, sẽ có lợi thế so với những đồng ít rõ ràng.", "response": "A", "reply": "Chính xác. Tôi sẽ ưu tiên stablecoin minh bạch hơn để giảm thiểu rủi ro trong danh mục đầu tư của mình."},
    {"sender": "A", "message": "Ok, chắc tôi sẽ dành thêm thời gian nghiên cứu về các hệ sinh thái Polkadot, Cardano, và stablecoin tuần này. Hẹn gặp lại tối nay nhé!", "response": "B", "reply": "Ok, tối nay cùng cập nhật thêm. Chúc mọi người giao dịch thuận lợi!"},
    {"sender": "B", "message": "Nhớ cập nhật thêm các dự án mới, đặc biệt là những dự án đang trong giai đoạn testnet hoặc whitelist. Đây là cơ hội tốt để vào sớm.", "response": "C", "reply": "Chắc chắn. Tôi sẽ tìm hiểu thêm và chia sẻ khi có thông tin thú vị!"},
    {"sender": "C", "message": "Chúc anh em may mắn tuần này. Đừng quên bảo toàn vốn và giữ vững tâm lý nhé!", "response": "A", "reply": "Cảm ơn mọi người. Hẹn gặp lại sau nhé!"}
]

conversation_script_3 = [
    {"sender": "A", "message": "Op nói chuẩn r đu strk từ 0.7 đến 1$ khá nhiều.", "response": "B", "reply": "Nhưng icp cũng vậy."},
    {"sender": "B", "message": "Hoặc là c98 kì lân.", "response": "C", "reply": "Đang rải truyền đơn."},
    {"sender": "C", "message": "H mua đợi mấy ae đu đỉnh về bờ là mình x3 x4 rùi.", "response": "A", "reply": "Đen lắm mua giống con này."},
    {"sender": "A", "message": "Mua rồi đợi thôi síp.", "response": "B", "reply": "Kỳ lân công nghệ Việt Nam nhé."},
    {"sender": "B", "message": "Fub to pump okee.", "response": "C", "reply": "Tg x3 a bán."},
    {"sender": "C", "message": "Đen gặp con đó đợi mãi k về được đâu.", "response": "A", "reply": "Bổ wld đi sirr."},
    {"sender": "A", "message": "Mấy con bay rồi nó bay nữa cũng không đáng kể.", "response": "B", "reply": "Ens qua link or fil."},
    {"sender": "B", "message": "Mua luôn tương lai ai cả thế giới shill.", "response": "C", "reply": "Ok để a đổi."},
    {"sender": "C", "message": "Đu đỉnh chung cho dui.", "response": "A", "reply": "Đồn vào 3 con thôi."},
    {"sender": "A", "message": "Đu đỉnh không chửi nhau là oke.", "response": "B", "reply": "Sáng ai mới bảo đu đỉnh thì chửi."},
    {"sender": "B", "message": "Cần oppa kéo chart khung W cho TP.", "response": "C", "reply": "Nhớ mua 1 con trend Ai nha."},
    {"sender": "C", "message": "Đù, z phải FDI ngủ thôi không ngồi tám xíu nữa đi swap hết ăn cám.", "response": "A", "reply": "Mà mua có 15$ không đủ trả tiền công oppa."},
    {"sender": "A", "message": "Hahahaha x3 là to lắm á.", "response": "B", "reply": "IO nghe giống tên miền."},
    {"sender": "B", "message": "AI nó ảo lắm a x10 cũng có.", "response": "C", "reply": "Lis bai nừn nữa nó bay như diều."},
    {"sender": "C", "message": "Không bít bao h bay thôi nhưng mà mỗi người thích 1 em.", "response": "A", "reply": "Oppa thích ngực bự."},
    {"sender": "A", "message": "Chờ trend thôi a cay.", "response": "B", "reply": "Allin hết con $lester cho emmm."},
    {"sender": "B", "message": "List Binance x2 làm con dân FOMO.", "response": "C", "reply": "Allin hết vào kèo sau."},
    {"sender": "C", "message": "Đang đáy cháy bằng niềm tin.", "response": "A", "reply": "Khuyên a ra đê ở hả."},
    {"sender": "A", "message": "A nhầm gì đó, a đánh x5 nó chỉ cần giảm 20% là a cháy.", "response": "B", "reply": "A đánh x2 nó chia 2 a mới cháy lệnh được."},
    {"sender": "B", "message": "Có con nào giảm 20% trong 1 ngày đâu.", "response": "C", "reply": "Nó chảy máu từ từ."},
    {"sender": "C", "message": "Bữa a đánh CET vs bỏ mẹ là quét sạch.", "response": "A", "reply": "Hôm cụ ỉa bữa vừa rồi."},
    {"sender": "A", "message": "Không có flo thôi a mua io rồi.", "response": "B", "reply": "Mua rồi thì xem chart ít thôi nha."},
    {"sender": "B", "message": "E là búp măng non không hiểu.", "response": "C", "reply": "Các a nói tiếng Việt em hiểu."},
    {"sender": "C", "message": "Flash GA cho ae lên ví. Mỗi ví 1dSOL là gì síp.", "response": "A", "reply": "Mấy síp chơi meme dùng từ chuyên ngành quá."},
    {"sender": "A", "message": "Mất niềm tin hàng Binance lỏ thật.", "response": "B", "reply": "Kiếm lowcap với midcap mà có MM chống lưng mà chơi sir."},
    {"sender": "B", "message": "Binance k chống được à oppa.", "response": "C", "reply": "Xin vài cái tên để check."},
    {"sender": "C", "message": "Không hiểu cách chơi của nó nó giam vốn cho ae mấy năm rồi chia xx để ae nhả hàng rồi mới đẩy.", "response": "A", "reply": "Nhưng mùa này uptrend phải đẩy thôi."},
    {"sender": "A", "message": "Coin công nghệ k thế tuỳ thôi.", "response": "B", "reply": "Mùa này siêu úp trend rồi."},
    {"sender": "B", "message": "E cũng bít nữa chỉ nêu ra quan điểm cá nhân thôi.", "response": "C", "reply": "Chắc sai."},
    {"sender": "C", "message": "KB bay bao nhiêu hoặc chọn con ngon chứ đúng là e giàu to rồi.", "response": "A", "reply": "Chứ năm trước sóng hồi giờ mới mùa."},
    {"sender": "A", "message": "Mà chửi C98 miệt thị TKO y chang né luôn.", "response": "B", "reply": "Theo e thì cứ giữ lại 1 ít biết đâu."},
    {"sender": "B", "message": "Khác nào hàng Indo với hàng Việt như nhau chung Binance Launch.", "response": "C", "reply": "Bán hết x10 tìm oppa."},
    {"sender": "C", "message": "Tại thấy Binance gom 1 cục hơn 20% rồi.", "response": "A", "reply": "Holder chẳng có tý cá mập nào toàn ví 0,01%."},
    {"sender": "A", "message": "Hình như C98 là Binance k còn nắm nhiều nữa pk nhỉ.", "response": "B", "reply": "Noooo e là thế anh không phải thế Khương."},
    {"sender": "B", "message": "Coin sàn CEX nó đỡ hơn C98 coin ví mà chart như nhau vkl.", "response": "C", "reply": "Moá như 2 giọt nước."},
    {"sender": "C", "message": "Đúng là chung 1 nhà cái đầu tư nãy em xem top holder.", "response": "A", "reply": "TKO 5$ cũng là 1 món quà của bọn Indo."},
    {"sender": "A", "message": "VC C98 5u là 1 món quà của bọn VN.", "response": "B", "reply": "Cười vcl không ngờ ở Indo cũng có phiên bản thứ 2 của C98."},
    {"sender": "B", "message": "Bữa có nghe KOL shill TKO list Launch xong mùa sau được Binance mua lại làm sàn của Binance ở Indo.", "response": "C", "reply": "Token làm lại hết. Nhưng chart vẫn giữ."},
    {"sender": "C", "message": "Là nó là sàn CEX thì xem qua về cộng đồng rồi sản phẩm của nó các thứ các thứ.", "response": "A", "reply": "Có khi cả thế giới mỗi nước có 1 cái bô của tụi Binance cũng nên."},
    {"sender": "A", "message": "DM cuộc đời DM meme ăn được đúng 1 con PNUT mua 0,1 lên 0,4 bán mịa rồi.", "response": "B", "reply": "Ụa thế x4 sao đu đỉnh nhiều vậy."},
    {"sender": "B", "message": "Toàn ATH mới âm 300.", "response": "C", "reply": "Mai Zawn có mấy bê mà cười dữ vậy."},
    {"sender": "C", "message": "Nịt a đứng trên 1 con voi cao dữ, ngon luôn.", "response": "A", "reply": "Cay mua SOL vs ETH đi Cay kiềm nó lại."},
    {"sender": "A", "message": "Xin tiền síp nổ ví Flash GA cho ae lên ví. Mỗi ví 1dSOL là gì síp.", "response": "B", "reply": "Mấy síp chơi meme dùng từ chiên ngành quá hỉu hem."},
    {"sender": "B", "message": "Síp bú kèo phọc môn chưa.", "response": "C", "reply": "Bữa giờ chưa bú kèo nào nên không biết kèo đó."},
    {"sender": "C", "message": "Bữa thấy síp làm mấy kèo liên quan đến nó mà.", "response": "A", "reply": "Iêm có cầm ETH không nếu có zia đội của a."},
    {"sender": "A", "message": "Ê tê hót sờ kem.", "response": "B", "reply": "E là búp măng non không hiểu."},
    {"sender": "B", "message": "Các a nói tiếng Việt em hiểu đã tiếng Anh còn viết tắt e không hiểu.", "response": "C", "reply": "Bữa sau e thêm chữ giúp a được không."},
    {"sender": "C", "message": "Các a trừ a cay a cay méo khác gì iêm đâu.", "response": "A", "reply": "Hahaha oki a cay."},
    {"sender": "A", "message": "Bên đó giờ thằng mod nó cầm 4 acc.", "response": "B", "reply": "Trùm report đến từ khu vực miền Nam."},
    {"sender": "B", "message": "Thêm 1 acc chống lưng spam a ớ bờ cờ nữa.", "response": "C", "reply": "Bữa a lấy hết 5 giải của nó."},
    {"sender": "C", "message": "Xíu e ban nó không biết sắp tới nó bật mấy tool đây.", "response": "A", "reply": "Nó sẽ ban a sớm thôi."},
    {"sender": "A", "message": "A vẫn để lại nó top 1 2 mà lấy top đó nó cay nó lại khóa mõm nhầm như e nữa :)))).", "response": "B", "reply": "A độc ác vãi l."},
    {"sender": "B", "message": "Bú hết pool DA quai.", "response": "C", "reply": "A làm gì đâu."},
    {"sender": "C", "message": "Bú bữa giờ không bằng e chơi poker.", "response": "A", "reply": "Nó sẽ đối xử với a như e đã từng thôi."},
    {"sender": "A", "message": "Còn phải hiểu cách đánh của nó nữa.", "response": "B", "reply": "Nhà cái vừa có tiền vừa có thời gian là làm giá được nữa."},
    {"sender": "B", "message": "Không hiểu cách chơi của nó nó giam vốn cho ae mấy năm rồi chia xx để ae nhả hàng rồi mới đẩy 🤣.", "response": "C", "reply": "Nhưng mùa này uptrend phải đẩy thôi."},
    {"sender": "C", "message": "Coin công nghệ không thế tùy thôi.", "response": "A", "reply": "Mùa này siêu úp trend rồi."},
    {"sender": "A", "message": "E cũng biết nữa chỉ nêu ra quan điểm cá nhân thôi.", "response": "B", "reply": "Chắc sai."},
    {"sender": "B", "message": "Không biết bay bao nhiêu hoặc chọn con ngon chứ đúng là e giàu to rồi.", "response": "C", "reply": "Chứ năm trước sóng hồi giờ mới mùa."},
    {"sender": "C", "message": "Mà chửi C98 miệt thị TKO y chang né luôn.", "response": "A", "reply": "Theo e thì cứ giữ lại 1 ít biết đâu."},
    {"sender": "A", "message": "Khác nào hàng Indo với hàng Việt như nhau chung Binance Launch.", "response": "B", "reply": "Bán hết x10 tìm oppa."},
    {"sender": "B", "message": "Tại thấy Binance gom 1 cục hơn 20% rồi.", "response": "C", "reply": "Holder chẳng có tý cá mập nào toàn ví 0,01%."},
    {"sender": "C", "message": "Hình như C98 là Binance không còn nắm nhiều nữa phải không nhỉ.", "response": "A", "reply": "Noooo e là thế anh không phải thế Khương."},
    {"sender": "A", "message": "Coin sàn CEX nó đỡ hơn C98 coin ví mà chart như nhau vkl.", "response": "B", "reply": "Moá như 2 giọt nước."},
    {"sender": "B", "message": "Đúng là chung 1 nhà cái đầu tư nãy em xem top holder.", "response": "C", "reply": "TKO 5$ cũng là 1 món quà của bọn Indo."},
    {"sender": "C", "message": "VC C98 5u là 1 món quà của bọn VN.", "response": "A", "reply": "Cười vcl không ngờ ở Indo cũng có phiên bản thứ 2 của C98."},
    {"sender": "A", "message": "Bữa có nghe KOL shill TKO list Launch xong mùa sau được Binance mua lại làm sàn của Binance ở Indo.", "response": "B", "reply": "Token làm lại hết. Nhưng chart vẫn giữ."},
    {"sender": "B", "message": "Là nó là sàn CEX thì xem qua về cộng đồng rồi sản phẩm của nó các thứ các thứ.", "response": "C", "reply": "Có khi cả thế giới mỗi nước có 1 cái bô của tụi Binance cũng nên."},
    {"sender": "C", "message": "DM cuộc đời DM meme ăn được đúng 1 con PNUT mua 0,1 lên 0,4 bán mịa rồi 😭😭😭😭.", "response": "A", "reply": "Ụa thế x4 sao đu đỉnh nhiều vậy."},
    {"sender": "A", "message": "Toàn ATH mới âm 300.", "response": "B", "reply": "Mai Zawn có mấy bê mà cười dữ vậy."},
    {"sender": "B", "message": "Nịt a đứng trên 1 con voi cao dữ, ngon luôn.", "response": "C", "reply": "Cay mua SOL vs ETH đi Cay kiềm nó lại."},
    {"sender": "C", "message": "Xin tiền síp nổ ví Flash GA cho ae lên ví. Mỗi ví 1dSOL là gì síp.", "response": "A", "reply": "Mấy síp chơi meme dùng từ chuyên ngành quá hiểu không."},
    {"sender": "A", "message": "Síp bú kèo phọc môn chưa.", "response": "B", "reply": "Bữa giờ chưa bú kèo nào nên không biết kèo đó."},
    {"sender": "B", "message": "Bữa thấy síp làm mấy kèo liên quan đến nó mà.", "response": "C", "reply": "Iêm có cầm ETH không nếu có zia đội của a."},
    {"sender": "C", "message": "Ê tê hót sờ kem.", "response": "A", "reply": "E là búp măng non không hiểu."},
    {"sender": "A", "message": "Các a nói tiếng Việt em hiểu đã tiếng Anh còn viết tắt e không hiểu.", "response": "B", "reply": "Bữa sau e thêm chữ giúp a được không."},
    {"sender": "B", "message": "Các a trừ a cay a cay méo khác gì iêm đâu.", "response": "C", "reply": "Hahaha oki a cay."},
    {"sender": "C", "message": "Bên đó giờ thằng mod nó cầm 4 acc.", "response": "A", "reply": "Trùm report đến từ khu vực miền Nam."},
    {"sender": "A", "message": "Thêm 1 acc chống lưng spam a ớ bờ cờ nữa.", "response": "B", "reply": "Bữa a lấy hết 5 giải của nó."},
    {"sender": "B", "message": "Xíu e ban nó không biết sắp tới nó bật mấy tool đây.", "response": "C", "reply": "Nó sẽ ban a sớm thôi."},
    {"sender": "C", "message": "A vẫn để lại nó top 1 2 mà lấy top đó nó cay nó lại khóa mõm nhầm như e nữa :)))).", "response": "A", "reply": "A độc ác vãi l."},
    {"sender": "A", "message": "Bú hết pool DA quai.", "response": "B", "reply": "A làm gì đâu."},
    {"sender": "B", "message": "Bú bữa giờ không bằng e chơi poker.", "response": "C", "reply": "Nó sẽ đối xử với a như e đã từng thôi."},
    {"sender": "A", "message": "Bú hết pool DA quai.", "response": "B", "reply": "A làm gì đâu."},
    {"sender": "B", "message": "Bú bữa giờ không bằng e chơi poker.", "response": "C", "reply": "Nó sẽ đối xử với a như e đã từng thôi."},
    {"sender": "C", "message": "Còn cái vụ memecoin nữa, sáng giờ oppa có hốt được gì không?", "response": "A", "reply": "Chưa, toàn thấy đám xả rồi kéo chart lừa gà."},
    {"sender": "A", "message": "Hôm qua mấy group call meme mà giờ đi bụi hết rồi.", "response": "B", "reply": "Hôm qua ăn được con nào không?"},
    {"sender": "B", "message": "Coi như mình góp quỹ cho dev thôi.", "response": "C", "reply": "Nó cầm hết token, còn gì nữa đâu mà mua."},
    {"sender": "C", "message": "Có khi nào hôm nay lại gặp pump không? Đỡ phải ngồi hóng.", "response": "A", "reply": "Hy vọng nhưng chắc khó, bữa giờ toàn pump fake."},
    {"sender": "A", "message": "C98 thì khỏi nói, 1 đống đu đỉnh đang ngồi khóc kia kìa.", "response": "B", "reply": "Vậy mà oppa vẫn call xả TKO được."},
    {"sender": "B", "message": "Giờ tìm cái lowcap ngon mà hold đi. Cái kiểu TKO hay C98 thì thôi.", "response": "C", "reply": "Biết đâu đấy, để vài năm nữa nó lên."},
    {"sender": "C", "message": "Hay là chuyển qua con AI trend thử xem?", "response": "A", "reply": "Hôm qua thấy chart đẹp lắm mà chưa dám vào."},
    {"sender": "A", "message": "Ai trend dễ ăn nhưng dễ mất, cần coi kèo kỹ hơn.", "response": "B", "reply": "Coi như đánh bạc thôi, trend mạnh thì phải thử."},
    {"sender": "B", "message": "Sáng mai xem có gì mới không rồi tính tiếp.", "response": "C", "reply": "Được, để coi nhóm nào call tốt thì nhảy vô."},
    {"sender": "C", "message": "Coi như sáng mai oppa dẫn đầu đi.", "response": "A", "reply": "Không đâu, mấy bữa trước tôi cũng đu đỉnh đấy."},
    {"sender": "A", "message": "Ai dám chơi với trend này nữa, mất tiền như chơi.", "response": "B", "reply": "Nhiều người ôm lâu giờ vẫn chưa về bờ đâu."},
    {"sender": "B", "message": "Mấy con lowcap kiểu này không dám vào, trend là đánh ngắn thôi.", "response": "C", "reply": "Chơi vậy thì phải tỉnh táo mới ăn được."},
    {"sender": "C", "message": "Oppa có list coin nào ngon không, share cho ae với.", "response": "A", "reply": "Để xem có gì thì tôi nói."},
    {"sender": "A", "message": "Chắc mai trend mạnh thì tôi vào, giờ cứ đợi.", "response": "B", "reply": "Được rồi, sáng call nhé."},
    {"sender": "B", "message": "Hy vọng mai không đu đỉnh nữa.", "response": "C", "reply": "Cố lên oppa, lấy lại những gì đã mất."},
    {"sender": "C", "message": "Còn oppa thích coin nào thì cứ call, ae chơi chung.", "response": "A", "reply": "Rồi, mai tính tiếp, ngủ thôi."},
    {"sender": "A", "message": "Được rồi, sáng mai call trend mạnh cho anh em chiến nhé.", "response": "B", "reply": "Ok, mai cứ TKO hay C98 thì né giúp nhé oppa."},
    {"sender": "B", "message": "Thấy trend AI bữa giờ ổn đấy, mà hơi sợ kéo xong xả.", "response": "C", "reply": "Trend mạnh vậy, không thử thì hơi phí."},
    {"sender": "C", "message": "Mấy con như FIL, LINK chart đang đẹp, oppa nghĩ sao?", "response": "A", "reply": "FIL thì ổn, LINK chắc cũng được nhưng phải coi thêm."},
    {"sender": "A", "message": "Hôm qua thấy nhóm call FIL x2 rồi mà giờ không biết có vào được không.", "response": "B", "reply": "FIL thấy vẫn tiềm năng, nhưng cẩn thận trend ngắn."},
    {"sender": "B", "message": "Mai FIL mà giảm mạnh chắc đón đáy thôi, ai cũng đang chờ.", "response": "C", "reply": "Tối nay check lại xem sao, sợ dev thả hàng bất ngờ."},
    {"sender": "C", "message": "Còn mấy con như ENS hay WLD thì sao? Nghe bảo trend cũng ổn.", "response": "A", "reply": "ENS là tên miền, trend này lên nhanh nhưng dễ xì."},
    {"sender": "A", "message": "WLD thì toàn mấy người chơi scan mống mắt, oppa nghĩ sao?", "response": "B", "reply": "WLD mà kéo thì dễ, nhưng hold thì không chắc lắm."},
    {"sender": "B", "message": "Thôi, cứ lowcap với trend mới đi. Highcap giờ bay không nổi đâu.", "response": "C", "reply": "Nói vậy cũng đúng, mai ai call trước thì vào sau."},
    {"sender": "C", "message": "Oppa, còn con nào x3 x5 dễ không, đừng khó quá.", "response": "A", "reply": "Khó nói, giờ toàn coin pump fake, nhưng mai tính tiếp."},
    {"sender": "A", "message": "Ngủ thôi, mai chiến tiếp nhé.", "response": "B", "reply": "Được rồi, oppa cứ chuẩn bị danh sách trend ngon."},
    {"sender": "B", "message": "Mai xem FIL, AI với ENS thử, chắc còn cửa.", "response": "C", "reply": "Ok, mai gặp lại, đừng đu đỉnh là được."},
    {"sender": "C", "message": "Rồi, mai gặp lại. Ngủ đi oppa, trend để mai tính.", "response": "A", "reply": "Chúc anh em tối nay mơ thấy x10 nhé."}
]
