conversation_script_1 = [
    {"sender": "A", "message": "Thứ khỏe rồi đi thôi.", "response": "B", "reply": "được bro, chỗ nào vip vậy?"},
    {"sender": "B", "message": "Đi cả ngày ko update anh em ơi.", "response": "A", "reply": "tải app về chưa? liên kết acc trên web chưa?"},
    {"sender": "A", "message": "Rồi ad, hôm qua đi thì đc hôm nay ko thấy update.", "response": "B", "reply": "vào web liên kết lại phát nữa. trên andiroi update chậm lắm."},
    {"sender": "B", "message": "chứ iphone cái 1 à.", "response": "A", "reply": "sida quá."},
    {"sender": "A", "message": "đc rồi.", "response": "B", "reply": "thank ad."},
    {"sender": "B", "message": "xếp hạng mấy vậy?", "response": "A", "reply": "500 rồi, xong 17 game, đang join 25 game."},
    {"sender": "A", "message": "nốt đi.", "response": "B", "reply": "15 nhiệm vụ đa dạng dễ dàng hoàn thành cho trader mới."},
    {"sender": "B", "message": "nhanh tay tham gia, phần thưởng giá trị cho người đầu tiên!", "response": "A", "reply": "cũng định làm mà SH250i k có bằng đi."},
    {"sender": "A", "message": "Base. Clank coin. Vào xổ số x5 ae ơi.", "response": "B", "reply": "kiếm lambo thôi thầy!"},
    {"sender": "B", "message": "Vậy mình người dùng cũ. Chim cút khỏi okx à?", "response": "A", "reply": "xem lambo chia nát."},
    {"sender": "A", "message": "E xin link vô mua a ơi.", "response": "B", "reply": "Nhanh ko dowtrend."},
    {"sender": "B", "message": "Sol bay ác thế mà bags k nổ đi còn chờ đợi gì nữa nhở.", "response": "A", "reply": "Sâu giá này thì mua về lm gì nhỉ."},
    {"sender": "A", "message": "Xổ số ae, min x2.", "response": "B", "reply": "ern lv35 max đk 13k. Thế mua sâu 15k vêd lm mẹ gì nhỉ."},
    {"sender": "B", "message": "Dc hoàn thêm 0.007 sui.", "response": "A", "reply": "x4 LOL!"},
    {"sender": "A", "message": "Bú ác.", "response": "B", "reply": "bào kiểu này rồi ko ai chơi lại khóc."},
    {"sender": "A", "message": "Mua sâu cúng hay làm gì má?", "response": "B", "reply": "Clm đen rồi ngày đầu chạy lại đau mắt cá chân."},
    {"sender": "B", "message": "Thôi toang 6 ngày còn lại r.", "response": "A", "reply": "Sao cno nhận đc."},
    {"sender": "A", "message": "Mà mình ko nhận đc nhỉ.", "response": "B", "reply": "bro join đc game này k."},
    {"sender": "B", "message": "Ko join đc nên mới hỏi.", "response": "A", "reply": "Dễ gì mà lên đ thế."},
    {"sender": "A", "message": "Lên vững chứ ko phải giật.", "response": "B", "reply": "nhanh hay chậm gì cũng chắc hết."},
    {"sender": "B", "message": "Công nhận.", "response": "A", "reply": "anh em mua stake di ido."},
    {"sender": "A", "message": "Sắp bay tới nơi.", "response": "B", "reply": "Giờ stake là đẹp."},
    {"sender": "B", "message": "come and arrest me.", "response": "A", "reply": "clm."},
    {"sender": "A", "message": "lắm ng tây vậy.", "response": "B", "reply": "Để xem."},
    {"sender": "B", "message": "Ese làm gì tiếp theo.", "response": "A", "reply": "Dạo này nhiều sự kiện quá."},
    {"sender": "A", "message": "Đúng r.", "response": "B", "reply": "Càng ngày càng có niềm tin."},
    {"sender": "B", "message": "Lại càng có động lực.", "response": "A", "reply": "Để chờ thêm."},
    {"sender": "A", "message": "Chứ gì nữa.", "response": "B", "reply": "chăm vay."},
    {"sender": "B", "message": "Đù.", "response": "A", "reply": "Éo ai được quà rồi."},
    {"sender": "A", "message": "Ese sắp list thêm CEX tier 1.", "response": "B", "reply": "Chuẩn bị bung lụa tiếp nhoá."},
    {"sender": "B", "message": "Oh.", "response": "A", "reply": "Tier 1 chắc binance."},
    {"sender": "A", "message": "gn.", "response": "B", "reply": "gud moning."},
    {"sender": "B", "message": "trường chào tân tráy quá.", "response": "A", "reply": "xem voi."},
    {"sender": "A", "message": "có ai the.", "response": "B", "reply": "Bigdaddy Emily sir."},
    {"sender": "B", "message": "Lê Bảo Minh Nhật.", "response": "A", "reply": "lineup chính thức là v."},
    {"sender": "A", "message": "này là ai.", "response": "B", "reply": "len tít tót sir."},
    {"sender": "B", "message": "chac ko hot.", "response": "A", "reply": "line up chính thức là v mà hqua lòi đâu ra Nam Per, Hoàng Cửu Bảo với Hoàng Tử Ếch."},
    {"sender": "A", "message": "thich ne.", "response": "B", "reply": "ổn hơn roi do."},
    {"sender": "B", "message": "cháy nhất Bắc Từ Liêm.", "response": "A", "reply": "có hát ko thầy."},
    {"sender": "A", "message": "có sir.", "response": "B", "reply": "Có ny ko?"},
    {"sender": "B", "message": "soon sir.", "response": "A", "reply": "Bú ko."},
    {"sender": "A", "message": "Chart đẹp vl.", "response": "B", "reply": "trend depin."},
    {"sender": "B", "message": "cho tele còn 10k.", "response": "A", "reply": "mua 1 lố rồi quay lại trend tele cũng được."},
    {"sender": "A", "message": "lạc quan quá síp.", "response": "B", "reply": "buy Op hold được rồi đó."},
    {"sender": "B", "message": "tầm này lạc quanlaf phải buy Pi Lét Quốc mà hold chứ.", "response": "A", "reply": "Hmmm."},
    {"sender": "A", "message": "pi víp quá e k đào.", "response": "B", "reply": "đào mtz thui."},
    {"sender": "B", "message": "ếch nhiêu tền là đủ dùng các síp nhỉ.", "response": "A", "reply": "399đ."},
    {"sender": "A", "message": "vkl.", "response": "B", "reply": "hèn gì síp bị elon khoá."},
    {"sender": "B", "message": "Hmmmm 399.", "response": "A", "reply": "Nó thả 7day die."},
    {"sender": "A", "message": "em mua từ 10k đến 20k có fl 20.", "response": "B", "reply": "chứ loại 5k e k dám."},
    {"sender": "B", "message": "a buy lúc 1.55 rồi.", "response": "A", "reply": "Á đù síp."},
    {"sender": "A", "message": "Trốn vk online.", "response": "B", "reply": "Ng có tiền gì cũng buy."},
    {"sender": "B", "message": "bth giờ này a vẫn onl mà.", "response": "A", "reply": "On claim mtz ?"},
    {"sender": "A", "message": "cái nào khó hỏi e.", "response": "B", "reply": "em gửi cái này."},
    {"sender": "B", "message": "khó.", "response": "A", "reply": "lên mmo mua."},
    {"sender": "A", "message": "nó mở mấy bữa n lại khóa cay vc.", "response": "B", "reply": "nhiêu cái nữa."},
    {"sender": "B", "message": "thiếu ý tưởng quá.", "response": "A", "reply": "1000 cái."},
    {"sender": "A", "message": "hmmm, k làm gì sao cứ khoá nhỉ.", "response": "B", "reply": "có dùng ip gì k síp."},
    {"sender": "B", "message": "Có lúc làm web 1 ip.", "response": "A", "reply": "Trên đt 1 ip khác."},
    {"sender": "A", "message": "Đậu.", "response": "B", "reply": "Vậy bth mà."},
    {"sender": "B", "message": "Thiếu 30 cái nữa hả.", "response": "A", "reply": "Sếp làm bn em lấy hết."},
    {"sender": "A", "message": "Xong gửi e ví.", "response": "B", "reply": "Mà nghỉ đi."},
    {"sender": "B", "message": "1,2 hôm có ý tưởng rồi bắt đầu.", "response": "A", "reply": "Editor."},
    {"sender": "A", "message": "Hhhh ko.", "response": "B", "reply": "Ý tưởng nhanh nhất lag đi copy rồi sửa."},
    {"sender": "B", "message": "Hiện tại chưa cần gấp.", "response": "A", "reply": "Để em sài hết đã."},
    {"sender": "A", "message": "Ủa cái plena kia.", "response": "B", "reply": "Nhiều mạng qua làm cái nào được."},
    {"sender": "B", "message": "Cái nào gas rẻ thì làm síp.", "response": "A", "reply": "Matic l2..."},
    {"sender": "A", "message": "Cứ cái nào là exp là múc hết hả.", "response": "B", "reply": "Né bnb avax ra."},
    {"sender": "B", "message": "Gas hơi cao.", "response": "A", "reply": "Oki."},
    {"sender": "A", "message": "Xong làm zealy.", "response": "B", "reply": "Mà zealy đang đua top với em dó."},
    {"sender": "B", "message": "Quần què toàn lagm x sợ vãi.", "response": "A", "reply": "Em làm tuốt."},
    {"sender": "A", "message": "1 lên voi 2 xuống x.", "response": "B", "reply": "Hhhh."},
    {"sender": "B", "message": "Làm bot tele plena. Có nhiệm vụ mint nft 1$.", "response": "A", "reply": "Cân nhădc."},
    {"sender": "A", "message": "Mạng gì ó.", "response": "B", "reply": "Quên r síp join tele nó hiện."},
    {"sender": "B", "message": "Oki.", "response": "A", "reply": "Hình như matic."},
    {"sender": "A", "message": "Rút tiền từ ví plena rút bằng $.", "response": "B", "reply": "Nên làm 1 ví chill."},
    {"sender": "B", "message": "Lagm chip hả tưởng vắt kiệt sức hhhh.", "response": "A", "reply": "1 acc chill síp."},
    {"sender": "A", "message": "Em 3x.", "response": "B", "reply": "Nó toag."},
    {"sender": "B", "message": "Làm tay 30acc.", "response": "A", "reply": "Hết nửa ngày à."},
    {"sender": "A", "message": "Trước khi làm thuyền trưởng.", "response": "B", "reply": "Thì con tàu chỉ mình tui."},
    {"sender": "B", "message": "Biến kẻ thù thành bạn. Là cách làm của mafia.", "response": "A", "reply": "ntn dc thì a đi xem tụi nó làm cái nào dễ."},
    {"sender": "A", "message": "a lấy về a sửa cho.", "response": "B", "reply": "được síp cho cái logo hình tròn, thêm tí chữ là oke."},
    {"sender": "B", "message": "khi nào a rảnh ý, em cần sll lớn mà a nên chỉnh bằng power point.", "response": "A", "reply": "hình này ok nè a."},
    {"sender": "A", "message": "biết chỉnh lại ó.", "response": "B", "reply": "A đi trông con đã."},
    {"sender": "B", "message": "okay síp.", "response": "A", "reply": "có gì rảnh giúp em nha."},
    {"sender": "A", "message": "Xíu gửi zô đâu z.", "response": "B", "reply": "nhờ 2 síp vô chơi 1 ván game cho nó tính ref với."},
    {"sender": "B", "message": "Hâhha.", "response": "A", "reply": "Ib box e."},
    {"sender": "A", "message": "Để e.", "response": "B", "reply": "Tag 2 síp đó."},
    {"sender": "B", "message": "cái này sao rồi síp.", "response": "A", "reply": "Nó cứ bị treo ấy a ạ."},
    {"sender": "A", "message": "tháng 12 TGE thì phải.", "response": "B", "reply": "lúc a bảo đó."},
    {"sender": "B", "message": "có chơi mà chơi nó toàn bị vầy.", "response": "A", "reply": "éo làm đc gì ko bị lose."},
    {"sender": "A", "message": "cay vcl.", "response": "B", "reply": "1000 cái nha."},
    {"sender": "B", "message": "Ước mơ của tôi.", "response": "A", "reply": "1 chos bằng 1 pen house."},
    {"sender": "A", "message": "này là hết nước đi mà.", "response": "B", "reply": "đủ rồi, thanks 2 ní."},
    {"sender": "B", "message": "Thánh ộp pô.", "response": "A", "reply": "Rank gì rồi síp."},
    {"sender": "A", "message": "Có tiền cứ đưa vợ hoặc nuôi vk tk khác nha các síp.", "response": "B", "reply": "Master."},
    {"sender": "B", "message": "Đừng đưa cho kol.", "response": "A", "reply": "yup."},
    {"sender": "A", "message": "xong đi ngủ.", "response": "B", "reply": "Đi guốc trong bụng."},
    {"sender": "B", "message": "thôi xong rồi.", "response": "A", "reply": "ngủ thâu, bibi."},
    {"sender": "A", "message": "e có bú ko.", "response": "B", "reply": "Làm cho e 100 con meme với síp."},
    {"sender": "B", "message": "Em trả lương.", "response": "A", "reply": "Bú gì sir."},
    {"sender": "A", "message": "tháng sau.", "response": "B", "reply": "K them."},
    {"sender": "B", "message": "Bú ngày 8$ ngon r a.", "response": "A", "reply": "Kkk."},
    {"sender": "A", "message": "uk.", "response": "B", "reply": "Rules khó k chơi."},
    {"sender": "B", "message": "khó thiệt.", "response": "A", "reply": "a up dàn ref lên để farm nên chơi luôn."},
    {"sender": "A", "message": "mà nghe khó.", "response": "B", "reply": "a mới 3$."},
    {"sender": "B", "message": "9 acc mà 3$.", "response": "A", "reply": "Vay vợ."},
    {"sender": "A", "message": "5tr úp hết đi a.", "response": "B", "reply": "Vay NH 500 tr."},
    {"sender": "B", "message": "Úp 1k acc.", "response": "A", "reply": "hú hú."},
    {"sender": "A", "message": "Oppa đu đỉnh k.", "response": "B", "reply": "dạo này bận săn sale quá."},
    {"sender": "B", "message": "có có.", "response": "A", "reply": "đu làm thanh khoản cho ae."},
    {"sender": "A", "message": "Thì vào team làm thanh khoản.", "response": "B", "reply": "ksao e a còn muốn giảm về 18 cơ. tích luỹ nhiều bứt phá càng mạnh."},
    {"sender": "B", "message": "Szybki KYC 20$ . 5 min.", "response": "A", "reply": "Về 18 rồi a ơi."},
    {"sender": "A", "message": "Múc thôi.", "response": "B", "reply": "Start."},
    {"sender": "B", "message": "Mấy anh em đẹp trai cho em xin 1 ref với.", "response": "A", "reply": "múc liên tục."},
    {"sender": "A", "message": "Mé hôm trc lên 25 e ko cắt. Cứ để đó nó xuống 18.", "response": "B", "reply": "Hôm đó mà cắt thì vào lại 18 ngon vãi."},
    {"sender": "B", "message": "Bao nhiêu vòng rồi. Số ko giàu dc.", "response": "A", "reply": "số thôi bảo r vẫn có điều chỉnh nhẹ, lại hồi ngay ý mà."},
    {"sender": "A", "message": "Chốt lời mà còn khó hơn gồng lỗ.", "response": "B", "reply": "Để hỏi trên nhóm xem có ko."},
    {"sender": "B", "message": "Síp hỏi giúp em với. Càng sớm càng tốt ạ.", "response": "A", "reply": "Số lương bao nhiêu thế."},
    {"sender": "A", "message": "Em mới out nên reff chậm.", "response": "B", "reply": "Ok để hỏi xem có ai ko."},
    {"sender": "B", "message": "Cái đó có vẻ ít.", "response": "A", "reply": "Lần đầu em làm nhiều thế."},
    {"sender": "A", "message": "Link nào để nó tính giá.", "response": "B", "reply": "Ib trực tiếp em nói gửi luôn được k síp."},
    {"sender": "B", "message": "Thế để xin tele rồi e nhắn nhé.", "response": "A", "reply": "Anh em nào có chơi con ocean bên sui ko."},
    {"sender": "A", "message": "Cái nhiệm vụ create meme anh em ai làm rồi chỉ tôi với.", "response": "B", "reply": "hê lô các con zời."},
    {"sender": "B", "message": "Game hệ TRON (TRX). Giữ 30 giây đc 0.25$. Ổn áp. May mắn sẽ thắng 1 chiếc Tesla. Xem bio nhé game này oker đó.", "response": "A", "reply": "ủa má pig trả r à quên mé luôn."},
    {"sender": "A", "message": "mấy nay bận quá k để ý. h vào thấy 0.003.", "response": "B", "reply": "nào thế e."},
    {"sender": "B", "message": "hnay tiếc chưa e.", "response": "A", "reply": "chốt mất r à."},
    {"sender": "A", "message": "E vẫn còn.", "response": "B", "reply": "Tại hôm qua đang lãi 1k6 mà quay đi cái nó tụt còn 1k nên thấy hoang mang. Sáng ra nó lại hồi lại rồi a."},
    {"sender": "B", "message": "Mé lãi gì cả ngàn đô thế.", "response": "A", "reply": "hâhhaha tăng ác vcc."},
    {"sender": "A", "message": "n sẽ điều chỉnh nhẹ mà.", "response": "B", "reply": "bh cứ thế tăng thôi."},
    {"sender": "B", "message": "kkkk.", "response": "A", "reply": "ông bạn a từ 5k lên 10k cmnr."},
    {"sender": "A", "message": "Ghê vãi ò. Nó cứ lên xuống ngon mà e toàn bị bất ngờ.", "response": "B", "reply": "Ko mua thêm dc nên ko dc bao nhiêu."},
    {"sender": "B", "message": "thôi giờ mua gì nữa.", "response": "A", "reply": "giữ đấy thôi."},
    {"sender": "A", "message": "n còn lên nữa.", "response": "B", "reply": "list coin base vs robinhood."},
    {"sender": "B", "message": "thì thôi kp nghĩ.", "response": "A", "reply": "Chắc bán thôi a."},
    {"sender": "A", "message": "Chọn 0.000023 rồi.", "response": "B", "reply": "no no e ơi."},
    {"sender": "B", "message": "nghe a.", "response": "A", "reply": "để đầu 5 thì bán."},
    {"sender": "A", "message": "nếu sợ thì đầu 4 thôi.", "response": "B", "reply": "k e cash out 50% cx đc."},
    {"sender": "A", "message": "Cắt bớt lấy tiền mua lại a ơi.", "response": "B", "reply": "Chứ e mua từ 0.000009."},
    {"sender": "B", "message": "Giờ x2.5 rồi.", "response": "A", "reply": "thích thì e cắt cx đc."},
    {"sender": "A", "message": "nhưng a nghĩ chả có điểm vào lại đâu.", "response": "B", "reply": "khó."},
    {"sender": "B", "message": "mua từ giá nào mà ghê v.", "response": "A", "reply": "cứ để thôi."},
    {"sender": "A", "message": "còn lên nữa.", "response": "B", "reply": "E x50."},
    {"sender": "B", "message": "Nên nhanh.", "response": "A", "reply": "à."},
    {"sender": "A", "message": "ra thế.", "response": "B", "reply": "Phải thế mới lẹ a à."},
    {"sender": "B", "message": "a để thấp quá.", "response": "A", "reply": "Lần trước ô trumb làm e cháy mất ít."},
    {"sender": "A", "message": "nảy chậm vcđ.", "response": "B", "reply": "Giờ cũng là ô trumb e lấy lại."},
    {"sender": "B", "message": "Mạnh mẽ lên a.", "response": "A", "reply": "Dc thì bú ko dc thì bay 1 chút."},
    {"sender": "A", "message": "Nay có gì mà bay ác.", "response": "B", "reply": "Btc gần 90k."},
    {"sender": "B", "message": "tối DCA thêm vào.", "response": "A", "reply": "chỉnh lại."},
    {"sender": "A", "message": "tối lợn trả tiền.", "response": "B", "reply": "lại có tiền DCA."},
    {"sender": "B", "message": "Đủ bữa nhậu ko.", "response": "A", "reply": "Kkk."},
    {"sender": "A", "message": "khéo chả đủ hộp sữa cho con.", "response": "B", "reply": "@@!"},
    {"sender": "B", "message": "k đủ quẳng vào thị trường tiếp.", "response": "A", "reply": "Hi."},
    {"sender": "A", "message": "Vãi ò biết vậy nãy bán luôn.", "response": "B", "reply": "Giờ lại tụt hơn 200u."},
    {"sender": "B", "message": "Chán vãi ò.", "response": "A", "reply": "hhahha."},
    {"sender": "A", "message": "đừng lo lắng e.", "response": "B", "reply": "nếu tối nay chạm 16 thì để."},
    {"sender": "B", "message": "k thì bán.", "response": "A", "reply": "Mé bận có 1 tí mà giảm ghê v."},
    {"sender": "A", "message": "Chốt rồi mua lại ngon hơn a ơi.", "response": "B", "reply": "Hye."},
    {"sender": "B", "message": "Nhưng chắc cũng phải chạm 90k mới quay đầu dc.", "response": "A", "reply": "Chắc rung tí thôi."},
    {"sender": "A", "message": "rung tý thôi.", "response": "B", "reply": "kệ."},
    {"sender": "B", "message": "mấy jo list nhỉ ae.", "response": "A", "reply": "vào chưa thấy j."},
    {"sender": "A", "message": "ae canh để cả hết hả, ai hold ko, btc đang bay.", "response": "B", "reply": "chuẩn bị quất ae."},
    {"sender": "B", "message": "Giá cao.", "response": "A", "reply": "kakaak, cao thì fai nhanh tay xả hết bác."},
    {"sender": "A", "message": "Chuẩn bị nào ae ơi.", "response": "B", "reply": "Ai nhanh tay dc giá cao."},
    {"sender": "B", "message": "Ai chậm tay giá thấp.", "response": "A", "reply": "kakakaka."},
    {"sender": "A", "message": "zô bú.", "response": "B", "reply": "0.007"},
    {"sender": "A", "message": "nãy fomo chơi tí, giờ ngồi chờ hồi thôi.", "response": "B", "reply": "@Congminhf, phong bạc không? Gửi lên phong bạc chơi cho vui."},
    {"sender": "B", "message": "nằm im đợi bú thôi em. kkk. không nhanh là mất cơ hội.", "response": "A", "reply": "oke anh. ARTFI cũng 100$ =))."},
    {"sender": "A", "message": "má rải mỗi con 100$. em vẫn hold mà, không biết bao giờ hồi.", "response": "B", "reply": "có gì chat ở đây cho vui. con lỏ Lescos bay kia mà scam vl mẹ nó."},
    {"sender": "B", "message": "thôi bỏ qua, thành khoản haha. chắc chẳng làm được gì hơn.", "response": "A", "reply": "má nó cay. mất 20u. thôi dca ARTFI, cố gỡ lại ít."},
    {"sender": "A", "message": "má để avatar gr chill vậy à? làm cho thấy thoải mái hơn à?", "response": "B", "reply": "kkk. chill mà, giờ ôm thì phải kiên nhẫn thôi."},
    {"sender": "B", "message": "mà con Pepe anh nhắc hồi nãy có vẻ lên được rồi. đánh giá sao?", "response": "A", "reply": "em thấy ổn, chắc hồi thêm chút nữa thì cân nhắc chốt."},
    {"sender": "A", "message": "anh nghĩ nên giữ lâu không? hay chốt sớm để dca tiếp?", "response": "B", "reply": "tùy, nhưng anh nghĩ giữ thêm chút nữa. con này tiềm năng."},
    {"sender": "B", "message": "con OP của em thế nào rồi? đã thấy nhúc nhích chưa?", "response": "A", "reply": "vẫn nằm im, cay thật sự. đang tính giảm bớt để thêm vào meme hệ Sol."},
    {"sender": "A", "message": "có meme nào đang nổi không? gợi ý anh vài con đi.", "response": "B", "reply": "anh xem con LESTER đi, nhưng cẩn thận, đừng dồn quá nhiều vốn."},
    {"sender": "B", "message": "mấy hôm nay BTC cứ tăng giảm khó lường. hold lâu thì hơi mệt.", "response": "A", "reply": "đúng rồi, nhưng chắc tới cuối tuần sẽ có sóng. chờ thêm tí."},
    {"sender": "A", "message": "oke, để xem sao. tối nay thử thêm lệnh nhẹ BTC nhé?", "response": "B", "reply": "chốt đấy. nhớ giữ vốn an toàn. thắng được thì mời nhậu!"},
    {"sender": "B", "message": "ARTFI nghe đâu cuối tuần có event. em cân nhắc tham gia không?", "response": "A", "reply": "để em xem sao. nhưng chắc không all-in đâu, phải cẩn thận."},
    {"sender": "A", "message": "trend này vẫn giữ được lâu không? hay sắp hết nhiệt rồi?", "response": "B", "reply": "chưa biết, nhưng volume đang giảm, có lẽ chỉ vài hôm nữa thôi."},
    {"sender": "B", "message": "con Pepe lúc nãy ông chốt chưa? thấy hồi lại mạnh rồi đó.", "response": "A", "reply": "chưa, đang ngồi canh. nhưng chắc mai chốt để nhẹ đầu."},
    {"sender": "A", "message": "suy nghĩ kỹ nhé. vì pump kiểu này dễ bị xả lắm.", "response": "B", "reply": "oke, cảm ơn ông. để tôi xem lại chart đã."},
    {"sender": "B", "message": "anh em trong nhóm kêu làm thêm task ARB. ông thử chưa?", "response": "A", "reply": "chưa, nhưng nghe bảo dễ làm. chắc tối nay test luôn."},
    {"sender": "A", "message": "test đi. biết đâu kiếm được ít token rồi hold lâu dài.", "response": "B", "reply": "vâng, giờ kiếm cái gì an toàn cũng tốt hơn là fomo."}
]
